import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {chromium} from '/home/reidsurmeier/.npm-global/lib/node_modules/playwright/index.mjs';

const url=process.argv[2];
assert(url?.startsWith('https://'),'Pass the deployed HTTPS URL.');
const evidence=process.env.BOOTH_DEPLOY_EVIDENCE??'/tmp/webcam-deployment';
const args=['--no-sandbox','--use-fake-device-for-media-stream','--enable-unsafe-swiftshader'];
if(process.env.BOOTH_DEPLOY_RESOLVE)args.push('--host-resolver-rules=MAP '+process.env.BOOTH_DEPLOY_RESOLVE);
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args});
try {
 const page=await browser.newPage({viewport:{width:1024,height:700},permissions:['camera']});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const photo='data:image/png;base64,'+(await readFile(new URL('../assets/photo-fixture.png',import.meta.url))).toString('base64');
 await page.addInitScript(photo=>{navigator.mediaDevices.getUserMedia=async()=>{const canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;const image=new Image();image.src=photo;await image.decode();canvas.getContext('2d').drawImage(image,0,0,640,480);return canvas.captureStream(10)}},photo);
 let interceptedRequests=0;const sample=await readFile(new URL('../assets/sample-portrait.webp',import.meta.url));await page.route('**/api/portrait',route=>{interceptedRequests++;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({image:'data:image/webp;base64,'+sample.toString('base64'),run:'unpaid-deploy-check'})});});
 const session=await page.context().newCDPSession(page);
 await session.send('Network.enable');
 await session.send('Network.emulateNetworkConditions',{offline:false,latency:20,downloadThroughput:1_250_000,uploadThroughput:500_000});
 const started=performance.now();await page.goto(url);
 await page.waitForFunction(()=>window.boothState?.state==='camera',null,{timeout:60000});
 const readyMs=Math.round(performance.now()-started);
 const wasm=await page.evaluate(()=>performance.getEntriesByType('resource').find(e=>e.name.endsWith('/index.wasm')).toJSON());
 assert(await page.evaluate(()=>window.isSecureContext));
 await page.getByRole('button',{name:'Enable camera',exact:true}).click();
 await page.waitForFunction(()=>window.boothState.source==='camera');
 await page.screenshot({path:evidence+'-camera.png'});
 await page.getByRole('button',{name:'Take picture',exact:true}).click();
 await page.waitForFunction(()=>window.boothState.state==='portrait');
 await page.screenshot({path:evidence+'.png'});
 await page.waitForFunction(()=>window.boothState.state==='explosion',null,{timeout:15000});
 assert(await page.evaluate(()=>window.boothState.motion_time>=10));
 await page.waitForFunction(()=>window.boothState.state==='camera',null,{timeout:15000});
 assert.equal(await page.evaluate(()=>window.boothState.has_capture),false);
 assert.equal(interceptedRequests,1);assert.deepEqual(errors,[]);
 const result={url,readyMs,networkMbps:10,wasm,paidRequests:0,interceptedRequests,cameraLoop:true};
 await writeFile(evidence+'.json',JSON.stringify(result,null,2)+'\n');
 console.log(JSON.stringify({readyMs,wasmBytes:wasm.encodedBodySize,wasmDecodedBytes:wasm.decodedBodySize,cameraLoop:true,paidRequests:0,interceptedRequests}));
 assert(wasm.encodedBodySize<15_000_000,'The engine download must be compressed below 15 MB.');
 assert(readyMs<25_000,'Cold startup must be under 25 seconds on the fixed 10 Mbps check.');
}finally {await browser.close();}
