// Exercise real HTTP composition and native run-record telemetry with an unpaid delayed adapter.
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,rm,symlink} from 'node:fs/promises';
import {resolve,join} from 'node:path';import {spawn} from 'node:child_process';import {once} from 'node:events';
const app=resolve(import.meta.dirname,'..'),temporary=await mkdtemp(resolve(app,'../.booth-progress-test-'));let child;
try{
 await mkdir(join(temporary,'server'));await mkdir(join(temporary,'build/private'),{recursive:true});await writeFile(join(temporary,'build/private/ledger.json'),'{"entries":{}}');await symlink(join(app,'server/generation.ts'),join(temporary,'server/generation.ts'));
 let source=await readFile(join(app,'server/server.ts'),'utf8');source=source.replace(/^const generate=.*;$/m,`let calls=0;const generate=capture=>Effect.tryPromise(async()=>{calls++;await new Promise(r=>setTimeout(r,5200));return {image:'data:image/png;base64,AAAA',run:'unpaid-'+calls}});`);assert(!source.includes('const generate=Effect.runSync'),'Unpaid adapter must replace generation');await writeFile(join(temporary,'server/server.ts'),source);
 child=spawn(process.execPath,['--experimental-strip-types',join(temporary,'server/server.ts')],{env:{PATH:process.env.PATH,BOOTH_PORT:'18138'},stdio:['ignore','pipe','pipe']});await Promise.race([once(child.stdout,'data'),once(child,'exit').then(()=>{throw Error('Test server exited')})]);
 const base='http://127.0.0.1:18138',id='01234567-0123-4123-8123-012345678901';const post=async(path,body,origin=base)=>{const r=await fetch(base+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Prefer:'respond-async'},body:JSON.stringify(body)});return {status:r.status,body:await r.json()}};const status=()=>post('/api/portrait/status',{id});
 assert.equal((await post('/api/portrait',{id,image:'data:image/png;base64,AAAA'})).status,202);assert.deepEqual((await status()).body.progress,{completed:0,total:4});
 const wrong=join(temporary,'artifacts/image-generation/runs/run-'+ 'a'.repeat(24));await mkdir(wrong,{recursive:true});await writeFile(join(wrong,'request.json'),JSON.stringify({references:[{applicationPath:'build/private/captures/other/subject.png'}]}));await writeFile(join(wrong,'state.json'),JSON.stringify({runId:'run-'+ 'a'.repeat(24),phase:'verified_candidate'}));assert.equal((await status()).body.progress.completed,0,'Other captures cannot advance progress');
 const run='run-'+ 'b'.repeat(24),runRoot=join(temporary,'artifacts/image-generation/runs',run);await mkdir(runRoot,{recursive:true});await writeFile(join(runRoot,'request.json'),JSON.stringify({references:[{applicationPath:`build/private/captures/${id}/subject.png`}]}));const phase=async value=>writeFile(join(runRoot,'state.json'),JSON.stringify({runId:run,phase:value}));
 await phase('submission_may_have_started');assert.equal((await status()).body.progress.completed,2);await new Promise(r=>setTimeout(r,4200));assert.equal((await status()).body.progress.completed,2,'Elapsed time alone must never advance progress');
 await phase('provider_evidence_received');assert.equal((await status()).body.progress.completed,3);await phase('reserved');assert.equal((await status()).body.progress.completed,3,'Completed milestones never regress');await writeFile(join(runRoot,'state.json'),'{');assert.equal((await status()).body.progress.completed,3,'Incomplete metadata is harmless');
 assert.equal((await post('/api/portrait/status',{id},'https://foreign.invalid')).status,403);await new Promise(r=>setTimeout(r,1100));assert.equal((await status()).body.run,'unpaid-1');assert.equal((await status()).body.run,'unpaid-1');assert.equal((await post('/api/portrait/status',{id:'missing'})).status,404);
 console.log('passed: matched native stages, >4s progress hold, monotonic milestones, wrong-run isolation, transient metadata, same-origin and one execution');
}finally{if(child){child.kill();await once(child,'exit')}await rm(temporary,{recursive:true,force:true})}
