from pathlib import Path
import json,shutil,urllib.request,re
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');build=root/'lowpoly-room-v41d-panels';app=Path('image-work/collection-room-remodel');e=Path('docs/evidence/collection-reconstruction/main-worker-medieval-panels-20261001T0845');public=root/'review-preview';review=public/'architecture-review-v41';game=public/'rockefeller-architecture-v41'
b=json.loads((build/'evidence/browser-result.json').read_text());assert b['pass'] and not b['errors'] and all(b['engine']['checks'].values())
check=Path('/tmp/collection-v41d-check.log').read_text();assert 'checks passed' in check
shell=Path('/tmp/collection-v41d-shell.log').read_text();passed=len(re.findall(r'^PASS ',shell,re.M));failed=len(re.findall(r'^FAIL ',shell,re.M));assert passed+failed==50
review.mkdir(exist_ok=False);shutil.copytree(build/'web',game)
for name in ['medieval-panel-bartolo.png','medieval-panel-virgin.png','medieval-panel-peter.png','medieval-north-panel-wide.png','medieval-portal-wall-wide.png','hall-source-camera.png','hall-wide-arch.png','portal-front.png','loop-overview.png']:
 shutil.copyfile(build/'evidence'/name,review/name)
for name in ['panel-66.75.png','panel-70.25.png','panel-72.75.png','panel-75.25.png','panel-85.75.png','panel-86.75.png','magdalene-frame-guide-v2.png','magdalene-frame-original.webp','magdalene-frame-v2b-original.webp','medieval-fit-85.75.png','medieval-fit-86.75.png','medieval-fit-87.25.png']:
 shutil.copyfile(e/name,review/name)
shutil.copyfile(build/'evidence/browser-result.json',review/'browser-result.json');shutil.copyfile(build/'geometry.json',review/'geometry.json');shutil.copyfile(app/'medieval-panel-source-fit.json',review/'placement-evidence.json')
def fig(name,caption):return f'<figure><a href="{name}"><img src="{name}" alt="{caption}" loading="lazy"></a><figcaption>{caption}</figcaption></figure>'
def pair(a,ac,b,bc):return '<div class="pair">'+fig(a,ac)+fig(b,bc)+'</div>'
html='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection medieval panels</title><style>body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto;max-height:1000px;object-fit:contain}figcaption{margin:6px 0 24px}</style><main><h1>Collection · medieval paintings and architecture</h1><p><a href="../rockefeller-architecture-v41/">Walk the current connected rooms</a> · <a href="../architecture-review-v40/">Previous pass and full room references</a></p><p>WASD to walk; Space resets; press 2 for the European gallery or 3 for the French gallery. Three verified medieval paintings now have their original outlines and integral gold borders on thin native wood panels. Their original museum images remain separate from generated frame trials. Exact object positions and room dimensions still need refinement.</p>'
html+=pair('panel-85.75.png','Video wide85.75s: Virgin on west wall; Magdalene and Saint Peter on north wall, followed by the projecting display.','medieval-north-panel-wide.png','Current corner: Virgin and Saint Peter installed, display projection and vents added. Magdalene remains missing until its generated frame is fitted. Lighting and exact mounting positions remain under review.')
for source,result,title in [('panel-66.75.png','medieval-panel-bartolo.png','Bartolo di Fredi Cini · Madonna and Child20.207'),('panel-70.25.png','medieval-panel-virgin.png','Matteo di Giovanni · Virgin of the Annunciation57.301'),('panel-75.25.png','medieval-panel-peter.png','Jacopo di Cione · The Taking of Saint Peter22.047')]:html+=pair(source,title+' · original video detail',result,title+' · actual native render, with original painting and exposed wood outline. Grey support and placement remain provisional.')
html+='<h2>Gabled frame for Mary Magdalene</h2><p>Two separate Muse passes cost$0.02. The first was rejected for an invented inner triangle and blue wear. The corrected source-shaped guide and owner-approved warm-gold style produced the second candidate below. It needs proportion fitting and native geometry before installation; the authentic painted panel will remain separate.</p>'
html+=pair('panel-72.75.png','Original museum frame around Lippo Memmi Mary Magdalene21.250.','magdalene-frame-guide-v2.png','Source guide: painted interior blanked while retaining the real gable and carved frame.')
html+=pair('magdalene-frame-original.webp','Rejected first pass: shortened opening and invented blue wear. Kept as failure evidence.','magdalene-frame-v2b-original.webp','Corrected Muse candidate: high pointed opening, three crockets per slope, twisted columns and warm gold. Source proportions and relief still unaccepted.')
html+=pair('medieval-fit-85.75.png','Source-local spacing ruler from the54×38.7cm Saint Peter panel. Hand picks and coplanar assumptions remain provisional.','medieval-fit-87.25.png','Held-out blurred wide: relative Magdalene/Peter spacing only. This does not prove exact room metres or object offsets.')
html+=pair('medieval-portal-wall-wide.png','Current portal wall. Missing iron grille and further sculptures/case contents are still open.','hall-wide-arch.png','Existing Main Hall connection and23 original paintings retained. Hall wall palette, frame heights and portal reverse need more work.')
html+=f'<p>Current RTX Chrome: {sum(b["engine"]["checks"].values())}/{len(b["engine"]["checks"])} navigation/camera checks plus a real keyboard round trip; p95{b["engine"]["frame_time_p95_ms"]:.2f}ms,ready{b["first_ready_ms"]}ms on the local test host.794 baked surfaces. Native detail and wide renders inspected; no new native performance claim. Owning Shell {passed}/50, {failed} failures retained. Repository checks pass.60fps target and remote cold-load performance remain unverified or unmet.</p><p>Cumulative generation spend$0.74 actual/$0.75 conservative. Heartbeat disabled; sole main worker. Still unfinished: exact room geometry and placement, gabled frame installation, missing room objects, stairs, auditorium and modern gallery.</p><p><a href="browser-result.json">Current browser checks</a> · <a href="placement-evidence.json">Placement evidence</a> · <a href="geometry.json">Current authored layout</a></p></main></html>'
(review/'index.html').write_text(html);(e/'review.html').write_text(html)
(public/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v41/"><a href="../architecture-review-v41/">Latest Collection reconstruction</a>')
url='https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/progress/'
with urllib.request.urlopen(url,timeout=30) as r:assert r.status==200
print('Published',url)
