from pathlib import Path
from PIL import Image
import json,shutil,urllib.request
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v38';share=root/'review-preview';review=share/'architecture-review-v38';e=Path('docs/evidence/collection-reconstruction/main-worker-bertin-20261001T0555')
a=json.loads((out/'evidence/walk-result.json').read_text());b=json.loads((out/'evidence/browser-result.json').read_text());assert all(a['checks'].values()) and b['pass'];assert 'NVIDIA' in a['renderer'] and 'NVIDIA' in b['webgl_renderer']
review.mkdir(exist_ok=False);shutil.copytree(out/'web',share/'rockefeller-architecture-v38')
for name in ['bertin-in-room','bertin-hall-wall','grey-gallery-wide','medieval-wide','browser-forward','browser-reverse','browser-jamb']:
 shutil.copyfile(out/'evidence'/f'{name}.png',review/f'{name}.png');shutil.copyfile(out/'evidence'/f'{name}.png',e/f'{name}.png')
for name in ['bertin-hall-wall','medieval-wide']:
 shutil.copyfile(root/'lowpoly-room-v37/evidence'/f'{name}.png',review/f'{name}-before.png');shutil.copyfile(root/'lowpoly-room-v37/evidence'/f'{name}.png',e/f'{name}-before.png')
for name in ['source-bertin-90.25.png','source-bertin-91.25.png']:
 im=Image.open(e/name);im.thumbnail((850,850));im.save(review/name)
for name in ['walk-result.json','browser-result.json']:shutil.copyfile(out/'evidence'/name,e/name);shutil.copyfile(out/'evidence'/name,review/name)
for name in ['geometry.json','manifest.json']:shutil.copyfile(out/name,review/name);shutil.copyfile(out/name,e/name)
def figure(path,caption):return f'<figure><img src="{path}" alt="{caption}" loading="lazy"><figcaption>{caption}</figcaption></figure>'
body='<h1>Collection rooms · Bertin and neutral grey-room light</h1><p><a href="../rockefeller-architecture-v38/">Walk the latest rooms</a> · <a href="../architecture-review-v36/">Previous case arrangement / source wides</a></p><p>Press 3 for the purple gallery and walk through the grey-room door; Bertin is on the wall beside the Hall entrance. The full Hall still needs joining.</p><div class="pair">'+figure('source-bertin-91.25.png','IMG_6380 91.25s: Bertin canvas and frame beside the Hall-door wall.')+figure('bertin-in-room.png','Official RISD 56.214 Tivoli canvas, one new Muse frame, source-relative bands. Exact relief/profile and offsets unaccepted.')+'</div><div class="pair">'+figure('bertin-hall-wall-before.png','Before: extra amber texture and warm fill made the grey wall brown.')+figure('bertin-hall-wall.png','Current: neutral plaster grain and neutral local fill, Main Hall cool ambient. Door geometry and room fit still provisional.')+'</div><div class="pair">'+figure('medieval-wide-before.png','Before: dark-room plaster had the same unwanted brown cast.')+figure('medieval-wide.png','Current: neutral dark-room palette. Two empty case shells; missing contents and wall sculptures remain unfinished.')+'</div><p>Native RTX and RTX Chrome '+str(len(a['checks']))+'/'+str(len(a['checks']))+' collision/camera checks; actual browser keyboard round trip passes. Native p95 '+str(round(a['frame_time_p95_ms'],2))+'ms; browser p95 '+str(round(b['engine']['frame_time_p95_ms'],2))+'ms. 593 lightmap surfaces rebuilt. Performance remains below 60fps target. Owning Shell failures are separately recorded; full reconstruction is not accepted.</p><p>One OpenRouter meta/muse-image output $0.01; cumulative $0.71 actual/$0.72 conservative. No paid lighting retry. Next: source-fit the complete Hall and adjoining room extents, then continue missing objects and architectural details. Collection only; heartbeat disabled.</p>'
style='body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto}figcaption{margin:6px 0 24px}'
page='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection source-matched Bertin and grey-room light</title><style>'+style+'</style><main>'+body+'</main></html>'
(review/'index.html').write_text(page);(e/'review.html').write_text(page)
(share/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v38/"><a href="../architecture-review-v38/">Latest Collection reconstruction</a>')
for path in ['progress/','architecture-review-v38/','rockefeller-architecture-v38/index.pck']:
 with urllib.request.urlopen('https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'+path,timeout=20) as r:assert r.status==200;print(path,r.status,r.headers.get('Content-Length'))
