from pathlib import Path
from PIL import Image
import json,shutil,urllib.request
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v36';share=root/'review-preview';review=share/'architecture-review-v36';e=Path('docs/evidence/collection-reconstruction/main-worker-medieval-cases-20261001T0525')
a=json.loads((out/'evidence/walk-result.json').read_text());b=json.loads((out/'evidence/browser-result.json').read_text());assert all(a['checks'].values()) and b['pass'];assert 'NVIDIA' in a['renderer'] and 'NVIDIA' in b['webgl_renderer']
review.mkdir(exist_ok=False);shutil.copytree(out/'web',share/'rockefeller-architecture-v36')
for name in ['medieval-wide','medieval-cases-east','medieval-cases-portal','phase-29','phase-30','phase-31','phase-32','browser-forward','browser-reverse','browser-jamb']:
 shutil.copyfile(out/'evidence'/f'{name}.png',review/f'{name}.png');shutil.copyfile(out/'evidence'/f'{name}.png',e/f'{name}.png')
for sec in ['78.25','88.75','96.25']:
 im=Image.open(e/f'source-{sec}.png');im.thumbnail((850,850));im.save(review/f'source-{sec}.png')
for sec in ['105.25','106.75']:
 im=Image.open(e/f'source-grey-hall-{sec}.png');im.thumbnail((850,850));im.save(review/f'source-grey-hall-{sec}.png')
for name in ['walk-result.json','browser-result.json']:shutil.copyfile(out/'evidence'/name,e/name);shutil.copyfile(out/'evidence'/name,review/name)
for name in ['geometry.json','manifest.json']:shutil.copyfile(out/name,review/name);shutil.copyfile(out/name,e/name)
def figure(path,caption):return f'<figure><img src="{path}" alt="{caption}" loading="lazy"><figcaption>{caption}</figcaption></figure>'
body='<h1>Collection rooms · medieval case placement</h1><p><a href="../rockefeller-architecture-v36/">Walk the latest rooms</a> · <a href="../architecture-review-v35/">Previous doorway correction</a> · <a href="../architecture-review-v34/wide-scale/">Hall scale study</a></p><p>Press 2 for the European gallery, then continue through the far double doors into Renaissance and turn right through the stone tracery doorway.</p><p>Reciprocal wide shots show two distinct case shapes and a staggered arrangement: a broad low relief case towards the middle, south-west of a smaller taller case near the stair doorway. Those previously missing case shells now have grey solid bases, white trays and separate glass heights.</p><div class="pair">'+figure('source-78.25.png','Actual low case in the foreground and tall case towards the stairs, IMG_6382 78.25s.')+figure('medieval-cases-east.png','New low and tall shells facing the same stair-side corner. Contents and wall sculptures are still missing.')+'</div><div class="pair">'+figure('source-88.75.png','Reciprocal view back towards the Romanesque portal, IMG_6382 88.75s.')+figure('medieval-cases-portal.png','Prototype view back towards the portal. Exact case dimensions/offsets remain provisional; the full Hall is not yet joined.')+'</div><div class="pair">'+figure('source-96.25.png','Source low glass hood, solid grey cabinet and white inset tray, IMG_6382 96.25s.')+figure('medieval-wide.png','Current two-case arrangement. Room extents, ceiling tracks, wall palette and doorway positions still need refinement.')+'</div><p>Native RTX and RTX Chrome pass '+str(len(a['checks']))+'/'+str(len(a['checks']))+' collision/camera checks, including both case bases and two clear routes. Browser keyboard round trip also passes. Native p95 '+str(round(a['frame_time_p95_ms'],2))+'ms; browser p95 '+str(round(b['engine']['frame_time_p95_ms'],2))+'ms. Below the 60fps target. Rebuilt native lightmap: 589 surfaces. Repository checks pass; frozen owning Shell remains 44/50 with the recorded layout/pixel/timing failures.</p><p>No new paid generation this pass. Existing Muse architecture and Main Hall shaders/presentation are retained; cumulative spend $0.70 actual/$0.71 conservative. Case contents are deliberately marked incomplete; no catalogue identity or full reconstruction acceptance is claimed. Next: fit the Hall entrance offsets, then source/API match and build the missing case contents, wall artworks and sculptures. Heartbeat stays disabled; Collection only.</p>'
style='body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto}figcaption{margin:6px 0 24px}'
page='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection medieval case placement</title><style>'+style+'</style><main>'+body+'</main></html>'
(review/'index.html').write_text(page);(e/'review.html').write_text(page)
(share/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v36/"><a href="../architecture-review-v36/">Latest Collection reconstruction</a>')
for path in ['progress/','architecture-review-v36/','rockefeller-architecture-v36/index.pck']:
 with urllib.request.urlopen('https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'+path,timeout=20) as r:assert r.status==200;print(path,r.status,r.headers.get('Content-Length'))
