from pathlib import Path
from PIL import Image
import json,shutil,urllib.request
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v39';share=root/'review-preview';review=share/'architecture-review-v39';e=Path('docs/evidence/collection-reconstruction/main-worker-hall-join-20261001T0620')
a=json.loads((out/'evidence/walk-result.json').read_text());b=json.loads((out/'evidence/browser-result.json').read_text());assert len(a['checks'])==66 and all(a['checks'].values()) and b['pass'];assert 'NVIDIA' in a['renderer'] and 'NVIDIA' in b['webgl_renderer']
review.mkdir(exist_ok=False);shutil.copytree(out/'web',share/'rockefeller-architecture-v39')
for name in ['perugino-in-room','perugino-walking','renaissance-wide','renaissance-door-wall','renaissance-door-corner','gallery-far-door','european-door-reverse','browser-forward','browser-reverse','browser-jamb']:
 shutil.copyfile(out/'evidence'/f'{name}.png',review/f'{name}.png');shutil.copyfile(out/'evidence'/f'{name}.png',e/f'{name}.png')
shutil.copyfile(root/'lowpoly-room-v38/evidence/renaissance-wide.png',review/'renaissance-before.png');shutil.copyfile(root/'lowpoly-room-v38/evidence/renaissance-wide.png',e/'renaissance-before.png')
for name in ['source-renaissance-35.75.png','source-renaissance-63.75.png','source-renaissance-64.75.png','annotated-hall-177.50.png','risd-official-floor5-map.png']:
 im=Image.open(e/name);im.thumbnail((1200,1200));im.save(review/name)
for name in ['walk-result.json','browser-result.json']:shutil.copyfile(out/'evidence'/name,e/name);shutil.copyfile(out/'evidence'/name,review/name)
for name in ['geometry.json','manifest.json']:shutil.copyfile(out/name,e/name);shutil.copyfile(out/name,review/name)
for name in ['wide-source-study.json','floorplan-source.json']:shutil.copyfile(e/name,review/name)
def figure(path,caption):return f'<figure><img src="{path}" alt="{caption}" loading="lazy"><figcaption>{caption}</figcaption></figure>'
body='<h1>Collection · Renaissance source comparison</h1><p><a href="../rockefeller-architecture-v39/">Walk the latest rooms</a> · <a href="../architecture-review-v38/">Previous grey-room pass</a></p><p>Use 2 for the European gallery and walk to its far end. The Renaissance room now has Perugino beside the door, a ventilation grille and light grey walls. Full reconstruction and the Grand Gallery connection are unfinished.</p>'
body+='<div class="pair">'+figure('source-renaissance-35.75.png','Native IMG_6383 35.75s: Perugino panel and architectural frame.')+figure('perugino-in-room.png','RISD API1546096 /16.236, original museum panel, one new Muse architectural frame. Brown derivative replaces the generated blue recesses. Visible support cropping, exact bands/depth and palette remain provisional.')+'</div>'
body+=figure('perugino-walking.png','Walking eye-height, actual376x252 Main Hall presentation; native painting and frame retain the shared shaders/bake.')
body+='<div class="pair">'+figure('renaissance-before.png','Before: warm ivory walls, no Perugino or north-door grille.')+figure('renaissance-wide.png','Current: neutral light grey and source-relative painting/grille. Exact room dimensions and missing case contents are unfinished.')+'</div>'
body+='<div class="pair">'+figure('source-renaissance-63.75.png','Native north doorway: triptych left, Perugino right. The triptych and display contents still need assets.')+figure('renaissance-door-wall.png','Current north door: two unequal panels and correct swing retained; doorway dimensions unchanged. Small-panel scale estimates disagree between the wide views, so no metric claim is made.')+'</div>'
body+='<div class="pair">'+figure('source-renaissance-64.75.png','Native reverse wide: doorway, Perugino and east-wall case/corner.')+figure('renaissance-door-corner.png','Current corner comparison. East-wall cases and their objects remain missing; offsets are provisional.')+'</div>'
body+='<div class="pair">'+figure('annotated-hall-177.50.png','Original Main Hall wide: end-door centre lies close to the wall midpoint. Offset end doors cannot be used to repair the current loop.')+figure('risd-official-floor5-map.png','Museum schematic: European gallery runs parallel to Grand Gallery. Diagram dated2020; topology aid only, no scale or current hang acceptance.')+'</div>'
body+='<p><a href="https://risdmuseum.org/visitor-guide/floor-5">RISD floor-five guide/map</a> · <a href="https://risdmuseum.org/art-design/collection/madonna-and-child-16236">Perugino catalogue</a> · <a href="wide-source-study.json">Manual wide study and rejected metric estimates</a></p>'
body+=f'<p>Native RTX and RTX Chrome66/66 collision/camera checks; actual browser keyboard round trip passes. Native p95{a["frame_time_p95_ms"]:.2f}ms; browser p95{b["engine"]["frame_time_p95_ms"]:.2f}ms.603 authored surfaces baked. Repeated-bake guard prevents including the previous lightmap meshes twice. Owning Shell failures are recorded in the checkpoint;60fps performance target is unmet.</p><p>One OpenRouter meta/muse-image output$0.01; cumulative$0.72 actual/$0.73 conservative. Heartbeat disabled. Next: fit the parallel European/Hall extents and end rooms together against the wide videos, then continue missing objects. Existing4.60m lateral/17.05m axial Hall-entry discrepancy is unresolved.</p>'
style='body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto}figcaption{margin:6px 0 24px}'
page='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection Renaissance source fit</title><style>'+style+'</style><main>'+body+'</main></html>'
(review/'index.html').write_text(page);(e/'review.html').write_text(page);(share/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v39/"><a href="../architecture-review-v39/">Latest Collection reconstruction</a>')
for path in ['progress/','architecture-review-v39/','rockefeller-architecture-v39/index.pck']:
 with urllib.request.urlopen('https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'+path,timeout=20) as r:assert r.status==200;print(path,r.status,r.headers.get('Content-Length'))
