const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
const url=process.argv[2],browser=await chromium.launch({headless:true,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1440,height:972}});
const errors=[];page.on('console',m=>console.log(m.type(),m.text()));page.on('requestfailed',r=>console.log('request failed',r.url(),r.failure()));page.on('pageerror',e=>errors.push(e.message));
await page.goto(url);await page.waitForFunction(()=>window.risdSearchProbe,null,{timeout:90000}).catch(async e=>{await page.screenshot({path:'/tmp/risd-search78/browser-failed.png'});throw e;});
const servedHash=createHash('sha256').update(await (await page.request.get(new URL('index.pck',url).href)).body()).digest('hex');
const localHash=createHash('sha256').update(await readFile('build/web-search-probe/index.pck')).digest('hex');assert.equal(servedHash,localHash);
const result=await page.evaluate(()=>window.risdSearchProbe);
assert.equal(result.search.ok,true,JSON.stringify(result));
assert.deepEqual(result.search.value.items.map(x=>x.id),['risd:1377691','risd:1584511']);
const wire=await page.evaluate(async()=>{const response=await fetch(new URL('api/collection/search?q=Monet&category=Painting',location.href));return {status:response.status,value:await response.json()}});
assert.equal(wire.status,200);assert.equal(wire.value.value.total,2);
assert.equal(errors.length,0,errors.join('\n'));
await page.screenshot({path:'/tmp/risd-search78/browser.png'});
await writeFile('/tmp/risd-search78/browser-report.json',JSON.stringify({url,result,wire,errors,servedHash},null,2));
console.log(JSON.stringify({records:result.search.value.items.map(x=>x.id),errors}));await browser.close();
