from pathlib import Path
from PIL import Image
import json,html,shutil
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v25';share=root/'review-preview';review=share/'architecture-review-v25';review.mkdir(exist_ok=True)
app=Path('image-work/collection-room-remodel');e=Path('docs/evidence/collection-reconstruction/main-worker-room-layout-20260930T2230')
qa=json.loads((out/'evidence/walk-result.json').read_text());browser=json.loads((out/'evidence/browser-result.json').read_text());assert all(qa['checks'].values()) and browser['pass']
shutil.copytree(out/'web',share/'rockefeller-architecture-v25',dirs_exist_ok=True)
for p in (out/'evidence').glob('*.png'):shutil.copyfile(p,review/p.name)
for p in e.glob('source-*.png'):
 im=Image.open(p);im.thumbnail((540,960));im.save(review/p.name)
for kind in ['romanesque-portal','tracery-arch']:
 im=Image.open(app/'trial'/f'{kind}-original.webp');im.thumbnail((880,720));im.save(review/f'{kind}-muse.webp')
geometry=json.loads((out/'geometry.json').read_text());shutil.copyfile(out/'geometry.json',review/'geometry.json')
svg=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 780 780"><rect width="780" height="780" fill="#faf7ef"/><text x="30" y="25" font-family="sans-serif" font-size="20">Source-confirmed connections · provisional room dimensions</text>']
for area in geometry['rooms']:
 x0,x1,z0,z1=area['bounds'];x=35+(x0+3.6)*19;y=65+(z0+7.2)*19;w=(x1-x0)*19;h=(z1-z0)*19
 color='#575762' if area['label']=='dark medieval room' else '#cbd4df' if area['label'].startswith('Main Hall') else '#eee3cb'
 svg.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{color}" stroke="#686357" stroke-width="2"/>')
 label=area['label'].replace(' threshold study limit',' · limit').replace(' doorway threshold study limit',' · limit')
 svg.append(f'<text x="{x+w+14}" y="{y+h/2}" font-family="sans-serif" font-size="13">{html.escape(label)}</text>')
 for side,span in area['openings'].items():
  if side in ['east','west']:dx=35+((x1 if side=='east' else x0)+3.6)*19;ax,bx=dx,dx;ay=65+(span[0]+7.2)*19;by=65+(span[1]+7.2)*19
  else:dy=65+((z1 if side=='south' else z0)+7.2)*19;ay,by=dy,dy;ax=35+(span[0]+3.6)*19;bx=35+(span[1]+3.6)*19
  svg.append(f'<line x1="{ax}" y1="{ay}" x2="{bx}" y2="{by}" stroke="#57936b" stroke-width="5"/>')
svg.append('<text x="30" y="760" font-family="sans-serif" font-size="13">Green = observed opening. Local axes; no compass claim. Main Hall/stairs remain short study limits.</text></svg>');(review/'layout.svg').write_text('\n'.join(svg)+'\n')
style='body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;align-items:flex-start;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto}figcaption{margin:6px 0 24px}'
body='<h1>Collection reconstruction · room layout v25</h1><p>The full 373-frame sculpture-room surveys show that the long gallery opens into the light Renaissance room, then a perpendicular side door leads into the dark medieval room. The medieval stone portal opens toward Main Hall; its stair doorway is on a different wall. Native room shells now follow those connections. Most displays are still missing, and exact room dimensions/object offsets remain provisional.</p><p><a href="../rockefeller-architecture-v25/">Open the walkable demo</a> · WASD move; Space reset; 1/2 earlier room views. Walk down the long gallery to inspect the two new rooms. <a href="../architecture-review-v21/">Previous gallery survey and demo</a>.</p><img src="layout.svg" alt="Provisional floor plan with observed room connections"><p><a href="geometry.json">Room geometry and collision-path record</a></p>'
def pair(items):
 return '<div class="pair">'+''.join('<figure><img loading="lazy" src="'+name+'" alt="'+html.escape(caption,quote=True)+'"><figcaption>'+caption+'</figcaption></figure>' for name,caption in items)+'</div>'
body+='<h2>Two distinct rooms, doors on perpendicular walls</h2>'+pair([('IMG_6383-121-144.jpg','Source wide shots: gallery doorway, adjacent books case, then Gothic doorway around the corner. All 147 frames reviewed.'),('renaissance-wide.png','Current shell: north gallery door and side Gothic door. Approximate camera; artwork/case contents not built yet.')])
body+='<h2>Romanesque Portal · 40.014</h2>'+pair([('source-portal-native.png','IMG_6382 at3.75s. Native video: round portal, paired engaged shafts, carved capitals and Main Hall beyond.'),('portal-front.png','One Muse pass, open native volume and collision. Catalogue height3.861m/width4.229m. Edge stepping, constant .45m depth and column relief are provisional.')])+pair([('romanesque-portal-muse.webp','Saved Muse raster · OpenRouter · $0.01. Official catalogue and current video were ordered references.'),('portal-angle.png','Baked native side view. Outer curve now has solid wall infill; only a short Main Hall threshold is modelled.')])+'<p><a href="https://risdmuseum.org/art-design/collection/romanesque-portal-40014">Official RISD record</a></p>'
body+='<h2>Tracery Arch · 40.156.1</h2>'+pair([('source-tracery-native.png','IMG_6383 at66.25s. Pointed top with asymmetric intertwined tracery.'),('tracery-front.png','Native holes remain open; catalogue fragment1.410 × 1.092 × .273m. Installed shafts and vertical placement inferred; carved profiles unfinished.')])+pair([('tracery-arch-muse.webp','One distinct Muse pass · OpenRouter · $0.01. Top fragment only; full installed doorway includes separate shafts.'),('tracery-angle.png','Side view of closed fragment extrusion and native shafts. Rear appearance and sculpture fidelity remain unaccepted.')])+'<p><a href="https://risdmuseum.org/art-design/collection/tracery-arch-401561">Official RISD record</a></p>'
body+='<h2>Dark room and floor</h2>'+pair([('IMG_6382-145-168.jpg','Reciprocal wide sweep: gold panels, round portal, stairs doorway, sculpture wall, then pointed Renaissance doorway. All 226 frames reviewed.'),('medieval-wide.png','Separate dark room with native herringbone floor. Sculptures, paintings and central cases are inventoried but not yet installed.')])
body+='<h2>Goltzius frame proportions</h2>'+pair([('source-goltzius-19.25.png','Sharper source view,19.25s; checked against18.25s. Planar corner estimates differ by up to28.35mm because the frame is stepped and the views are oblique.'),('goltzius-in-room.png','Saved Muse bands compressed to source estimates, keeping every blank-opening pixel and the original Muse raster unchanged. Catalogue painting61.006 stays separate; room position/gold facets/profile remain provisional.')])
body+=f'<h2>Checks and remaining work</h2><p>Native RTX4070SUPER: {len(qa["checks"])} / {len(qa["checks"])} collision/camera checks, p95 {qa["frame_time_p95_ms"]:.2f}ms. Chrome/RTX ANGLE: {len(browser["engine"]["checks"])} engine checks plus real keyboard round trip, no JS/runtime errors. Native LightmapGI: 417 surfaces, CPU software-Vulkan bake; runtime rendering on RTX. Performance remains below 60fps acceptance.</p><p>Repository checks passed. Shell playtest 44/50 twice: four existing layout/pixel failures plus pressed/dip timing failures. No Shell/Tab/Viewer edits. Two new Muse outputs cost $0.02; cumulative recorded map $0.64, conservative $0.65 including the unresolved central-deities submission. That run and failed head trials were not resubmitted.</p><p>870 frames fully reviewed across five videos; the other five video surveys, catalogue matching, most display assets, exact spacing, stone profiles and actual Main Hall integration remain unfinished. The full reconstruction goal is active; heartbeat remains disabled.</p><h2>All 17 sculpture survey sheets</h2>'
for p in sorted((root/'sculpture-rooms-survey-v1').glob('*.jpg')):
 shutil.copyfile(p,review/p.name);body+='<figure><img loading="lazy" src="'+p.name+'" alt="Survey frames in '+p.name+'"><figcaption>'+p.name+'</figcaption></figure>'
(review/'index.html').write_text('<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection room layout v25</title><style>'+style+'</style><main>'+body+'</main></html>')
(share/'progress/index.html').write_text('<!doctype html><html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v25/"><a href="../architecture-review-v25/">Latest Collection reconstruction progress</a></html>')
shutil.copyfile(review/'layout.svg',e/'layout.svg');print(review)
