from pathlib import Path
import json,shutil,urllib.request,hashlib,re
out=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion/lowpoly-room-v44b-grille');public=out.parent/'review-preview';e=Path('docs/evidence/collection-reconstruction/main-worker-iron-grille-20261001T1040');review=public/'architecture-review-v44';game=public/'rockefeller-architecture-v44';review.mkdir(exist_ok=False);shutil.copytree(out/'web',game)
b=json.loads((e/'browser-result.json').read_text());assert b['pass'] and len(b['engine']['checks'])==158 and all(b['engine']['checks'].values()) and b['errors']==[]
s=Path('/tmp/collection-v44b-shell-repeat.log').read_text();passed=len(re.findall('^PASS ',s,re.M));failed=len(re.findall('^FAIL ',s,re.M));assert passed+failed==50
names=['medieval-grille-front.png','medieval-grille-oblique.png','medieval-portal-wall-wide.png','medieval-wide.png','medieval-walk.png','renaissance-wide.png','hall-wide-arch.png','loop-overview.png','v43-portal-wall-wide.png','v44-thin-medieval-grille-front.png','grille-12.375-source.jpg','v42-grille-88.75-review.jpg','medieval-grille-rectified-study.png','medieval-grille-original.webp','iron-grille-native.json','browser-result.json','architecture-review.json','grille-v44-control-review.json']
for n in names:shutil.copyfile(e/n,review/n)
def fig(n,c):return f'<figure><a href="{n}"><img src="{n}" alt="{c}" loading="lazy"></a><figcaption>{c}</figcaption></figure>'
def pair(a,ac,b,bc):return '<div class="pair">'+fig(a,ac)+fig(b,bc)+'</div>'
html='''<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection · source-fitted iron grille study</title><style>body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto;max-height:1000px;object-fit:contain}figcaption{margin:6px 0 24px}</style><main><h1>Collection · source-fitted iron grille study</h1><p><a href="../rockefeller-architecture-v44/">Walk the updated connected rooms</a> · <a href="../architecture-review-v43/">Previous ceiling and lighting pass</a></p><p>WASD to walk; Space resets; 2 opens the European gallery, 3 the French gallery. The iron grille seen beside the medieval portal is now present as open low polygon geometry on a low white plinth. It uses seven source-observed columns and material pixels from the existing Muse pass. This is a placement and shape study: row count, irregular scroll pattern, handedness, exact scale, braces, plinth and location remain provisional. Catalogue identity is still unmatched. Full room layout and object coverage are unfinished.</p>'''
html+=pair('v42-grille-88.75-review.jpg','Wide source: grille right of the portal; stone wall fragment farther east beside a different stair opening. Flat ceiling and multiple track lights.','medieval-wide.png','Current baked room wide: grille added beside portal. Source wall fragment, stair doorway and lighting layout still need work; positions and room proportions are provisional.')
html+=pair('v43-portal-wall-wide.png','Previous pass: ceiling present, grille missing.','medieval-portal-wall-wide.png','Current wide: open grille and its plinth added. Existing Hall remains visible through the portal. Case contents and surrounding wall geometry are incomplete.')
html+=pair('grille-12.375-source.jpg','Native video source at12.375s: seven columns, irregular iron scrolls, wall brace and white plinth. Blur/perspective limit exact row counting and measurements.','medieval-grille-oblique.png','Native baked oblique: open scroll mesh, top rear support and colliding plinth. Plain profiles/uniform coils are a preliminary approximation, not accepted historical geometry.')
html+=pair('medieval-grille-rectified-study.png','Manually straightened source study; aspect and metres not calibrated. Seven columns observed, row count unverified.','medieval-grille-front.png','Current front: seven columns and17 provisional rows. Geometry closure verified independently for119 coil solids. Full grille union, source pattern and exact dimensions remain unaccepted.')
html+=pair('medieval-grille-original.webp','Existing$0.01 Muse sheet: eight columns, rejected for direct geometric installation. Only interior iron-post pixels reused in this pass.','v44-thin-medieval-grille-front.png','Retained earlier native trial: coils too thin/sparse and partly occluded by the foreground case. Revised mesh and front camera used in the current result.')
html+=pair('medieval-walk.png','Actual elevated walking view: authored/baked ceiling cutaway retained, grille blocks visitor passage and adjacent east aisle stays clear.','hall-wide-arch.png','Existing Main Hall presentation, lighting and23 verified paintings retained.')
html+=fig('loop-overview.png','Connected prototype circuit. This is not a verified complete museum map; room metres, doors, object positions and missing contents remain open.')
html+=f'''<p>RTX4070SUPER Chrome158/158 navigation/camera checks plus real keyboard round trip,33 continuous circuit segments,errors[],p95{b['engine']['frame_time_p95_ms']:.2f}ms.825 native baked surfaces; two authored ceilings and two baked copies retain visibility checks. Owning Shell{passed}/50,{failed} known failures retained in checkpoint evidence. Repository checks and diff whitespace checks pass after archived source copies were named.gd.txt instead of.gd. No new native performance claim;60fps target is unresolved.</p><p>RISD catalogue lookup:100-result requests returned misleading empty lists. Known-ID and Monet positive controls work with25; valid searches are retained, broad first pages are incomplete. No identity assigned. No new paid generation; total$0.75 actual/$0.76 conservative. Heartbeat disabled; sole main worker. Next compare reciprocal wide shots across the rooms, then correct the medieval east-wall fragment/stair doorway, light tracks and remaining object/door placements. Failed head meshes remain unaccepted.</p><p><a href="architecture-review.json">Source observations and uncertainties</a> · <a href="iron-grille-native.json">Independent native coil proof</a> · <a href="browser-result.json">Browser checks</a> · <a href="grille-v44-control-review.json">Catalogue query controls</a></p></main></html>'''
(review/'index.html').write_text(html);(e/'review.html').write_text(html)
base='https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'
for n in ['architecture-review-v44/','architecture-review-v44/medieval-grille-front.png','rockefeller-architecture-v44/','rockefeller-architecture-v44/index.pck']:
 with urllib.request.urlopen(base+n,timeout=30) as r:assert r.status==200
(public/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v44/"><a href="../architecture-review-v44/">Latest Collection reconstruction</a>')
(e/'SHA256.json').write_text(json.dumps({str(p.relative_to(e)):hashlib.sha256(p.read_bytes()).hexdigest() for p in e.rglob('*') if p.is_file() and p.name!='SHA256.json'},indent=2)+'\n')
print('Published',base+'progress/')
