from pathlib import Path
from PIL import Image
import hashlib,json,subprocess
app=Path('image-work/collection-room-remodel').resolve();kind='ionic-capital';assert not (app/f'{kind}-receipt.json').exists(),'Reconcile any prior submission before spending'
source=Path('/tmp/collection-ionic-wide-native.png');refs=[]
for i,im in enumerate([Image.open(source).convert('RGB').crop((190,180,665,505)),Image.open(source).convert('RGB'),Image.open(app/'inventory-references/purple-plaster-selected-1.png').convert('RGB')]):
 p=app/'inventory-references'/f'{kind}-selected-{i}.png';im.save(p);refs.append({'path':str(p.relative_to(app)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
prompt='Generate ONE complete FRONT ORTHOGRAPHIC low polygon Ionic column CAPITAL matching the white-painted historic RISD grey-gallery column top in reference1 and its architectural context in reference2. Preserve the paired downward-curling spiral volutes left and right, shallow curved band between them, short round neck beneath, and thin rectangular square abacus above. The actual shaft is smooth and unfluted; include only a very short neck, not a whole column. Warm off-white painted plaster, restrained facet shading consistent with reference3 museum game, simple shallow moulding relief. Complete silhouette and all scrolls, generous magenta #FF00FF outside background. One capital only, no entablature, shaft, base, wall, floor, people, labels, detached parts or cast shadow outside silhouette. Frontal orthographic view, no perspective. Do not add Corinthian leaves, heads, statues or gilding. Native closed geometry will supply depth; preserve the characteristic twin-scroll silhouette.'
p=app/f'{kind}-prompt.txt';p.write_text(prompt+'\n');plan={'attempts':[{'id':kind+'-001','prompt':p.name,'promptSha256':hashlib.sha256(p.read_bytes()).hexdigest(),'size':'1760x1440','inputs':refs}]};(app/f'{kind}-plan.json').write_text(json.dumps(plan,indent=2)+'\n');(app/f'{kind}-recipe.json').write_text(json.dumps({'procedure':'edit','plan':kind+'-plan.json','attempt':kind+'-001'})+'\n');(app/f'{kind}-source.json').write_text(json.dumps({'source_video':'IMG_6380.MOV','time_seconds':34.25,'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'accepted':False,'hidden_geometry':'Capital side/rear depth and exact dimensions unmeasured; source-guided low polygon trial'},indent=2)+'\n')
cli=['node','/home/reidsurmeier/Image-generation-pipline/.tool-builds/1790783219515/scripts/image-pipeline.js'];r=subprocess.run(cli+['prepare','--application',str(app),'--recipe',kind+'-recipe.json','--unit-cost','0.01','--budget','0.01'],capture_output=True,text=True);assert r.returncode==0,r.stdout;(app/f'{kind}-prepared.json').write_text(r.stdout);objective=json.loads(r.stdout)['objective'];r=subprocess.run(cli+['image','--application',str(app),'--objective',objective],capture_output=True,text=True);assert r.returncode==0,r.stdout;(app/f'{kind}-planned.json').write_text(r.stdout);assert json.loads(r.stdout)['_tag']=='Planned';Path('/tmp/collection-ionic-plan-result.json').write_text(json.dumps({'kind':kind,'objective':objective})+'\n');print('One capital planned, $0.01 ceiling, source hashes retained')
