from pathlib import Path
from PIL import Image
import json,shutil,html
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v34';share=root/'review-preview';review=share/'architecture-review-v34';app=Path('image-work/collection-room-remodel');e=Path('docs/evidence/collection-reconstruction/main-worker-ionic-20261001T0400')
a=json.loads((out/'evidence/walk-result.json').read_text());b=json.loads((out/'evidence/browser-result.json').read_text());assert all(a['checks'].values()) and b['pass'];assert 'NVIDIA' in a['renderer'] and 'NVIDIA' in b['webgl_renderer']
review.mkdir(exist_ok=True);shutil.copytree(out/'web',share/'rockefeller-architecture-v34',dirs_exist_ok=True)
for name in ['purple-grey-wide','grey-purple-reverse','grey-door-corner','courbet-in-room','corot-in-room','grey-walk','ionic-capital-front','ionic-capital-oblique','room','browser-forward','browser-reverse','browser-jamb']:
 shutil.copyfile(out/'evidence'/f'{name}.png',review/f'{name}.png')
for kind in ['courbet-frame','corot-frame','white-panel-door']:
 im=Image.open(app/'trial'/f'{kind}-original.webp');im.thumbnail((850,850));im.save(review/f'{kind}-muse.webp')
for name,src in [('source-courbet','/tmp/collection-courbet-frame-native.png'),('source-corot','/tmp/collection-corot-frame-complete-native.png'),('source-door','/tmp/collection-white-panel-door-native.png')]:
 im=Image.open(src);im.thumbnail((850,850));im.save(review/f'{name}.png')
for name,src in [('source-ionic','/tmp/collection-ionic-wide-native.png'),('ionic-capital-muse',str(app/'trial/ionic-capital-original.webp'))]:
 im=Image.open(src);im.thumbnail((850,850));im.save(review/f'{name}.png')
shutil.copyfile(e/'loop-spacing-check.json',review/'loop-spacing-check.json')
for name in ['geometry.json','manifest.json']:shutil.copyfile(out/name,review/name)
for name in ['hall-stairs-inventory.json','reconstruction-coverage.json','grey-frames-source-fit.json']:shutil.copyfile(app/name,review/name)
rooms=json.loads((out/'geometry.json').read_text())['rooms'];parts=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 1130"><rect width="760" height="1130" fill="#f3eee3"/><text x="20" y="30" font-size="18">Current native shells · dimensions provisional · blue = threshold limit</text>']
for i,r in enumerate(rooms):
 x0,x1,z0,z1=r['bounds'];x=(x0+4)*30+20;y=(z0+8)*30+65;w=(x1-x0)*30;h=(z1-z0)*30;col='#bdcbd4' if 'threshold' in r['label'] else '#c4afd1' if 'purple' in r['label'] else '#ddd2bb'
 parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{col}" stroke="#574c3b" stroke-width="2"/><text x="{x+5}" y="{y+19}" font-size="13">{i+1}</text>')
 for side,opening in r['openings'].items():
  lo,hi=opening
  if side in ['west','east']:
   xx=((x0 if side=='west' else x1)+4)*30+20;coords=[xx,(lo+8)*30+65,xx,(hi+8)*30+65]
  else:
   yy=((z0 if side=='north' else z1)+8)*30+65;coords=[(lo+4)*30+20,yy,(hi+4)*30+20,yy]
  parts.append('<line x1="%s" y1="%s" x2="%s" y2="%s" stroke="#f3eee3" stroke-width="5"/>'%tuple(coords))
parts.append('</svg>');(review/'layout.svg').write_text(''.join(parts));shutil.copyfile(review/'layout.svg',e/'layout.svg')
def pair(items):return '<div class="pair">'+''.join('<figure><img loading="lazy" src="'+n+'" alt="'+html.escape(c,quote=True)+'"><figcaption>'+c+'</figcaption></figure>' for n,c in items)+'</div>'
body='<h1>Collection · grey-gallery connection v34</h1><p><a href="../rockefeller-architecture-v34/">Open the walkable demo</a> · WASD · Space reset · 1 Rockefeller · 2 European gallery · 3 grey gallery. <a href="../architecture-review-v26/">Previous corrections and all ten video surveys</a>.</p><p>The purple connector now reaches the grey French gallery. The Ionic opening faces it across the room; the piano and Grand Gallery doors are on perpendicular adjoining walls. Three-paneled open door leaves, two museum paintings and twin-scroll Muse Ionic capitals are installed. All room dimensions, camera fits and object offsets remain provisional. Full Grand Gallery/stair rooms and most grey-gallery contents remain unfinished; the three blue threshold limits are closed study ends.</p>'
body+=pair([('../architecture-review-v26/IMG_6380-481-504.jpg','Reciprocal source wide views: straight purple connector into grey room, Ionic entrance ahead.'),('purple-grey-wide.png','Current authored connector and grey room. Muse capitals now installed; entablature and source sculpture still missing; doorway metric fit unaccepted.')])+pair([('grey-purple-reverse.png','Reverse view toward Rockefeller: black panels face purple elevator wall.'),('grey-door-corner.png','Perpendicular Grand Gallery entrance beside purple connector. Full blue Main Hall still separate from this threshold.')])
body+=pair([('source-ionic.png','Native video context at6380:34.25s: smooth shaft, twin-scroll capital and dentil beam above.'),('ionic-capital-muse.png','New original Muse capital; $0.01, preserved intact. Native mesh supplies provisional closed depth.')])
body+=pair([('ionic-capital-front.png','New Muse twin-scroll capital; closed 1928-triangle silhouette, width/height/depth provisional.'),('ionic-capital-oblique.png','Oblique source-guided profile. Constant-depth extrusion repeats frontal colour; carved volute relief and reverse remain unaccepted.')])
body+='<h2>Two distinct Muse frames, official museum paintings</h2>'+pair([('source-courbet.png','Source Courbet43.571; frame with projecting carved foliage.'),('courbet-in-room.png','Muse frame around official painting. Bands fitted using provisional planar corners; hidden depth and ornament remain unaccepted.')])+pair([('source-corot.png','Source Corot24.089; simple gold/black rectangular frame.'),('corot-in-room.png','Separate Muse frame around the official painting. Exact catalogue support/frame distinction and nonplanar dimensions remain unverified.')])
body+=pair([('courbet-frame-muse.webp','Original Courbet Muse output; $0.01, retained intact.'),('corot-frame-muse.webp','Original Corot Muse output; $0.01, retained intact.')])+pair([('source-door.png','Source white door leaf: unequal panels, open into Grand Gallery.'),('white-panel-door-muse.webp','Original Muse output; $0.01. Generated extra jamb excluded; three panels assembled around native rails/stiles. Exact heights/hardware and reverse remain unfinished.')])
body+='<p>Also matched Villeneuve Roman Aqueduct1998.35 at6380:86.25s, Daubigny Landscape73.120 at6380:25.25s and Pannini The Colosseum56.094 to source6380:190–195 and official RISD image; its new frame and placement are not yet installed. <a href="hall-stairs-inventory.json">Survey inventory and nine new RISD matches</a> · <a href="grey-frames-source-fit.json">Provisional frame corner fits</a> · <a href="reconstruction-coverage.json">Remaining acceptance</a>.</p><p><a href="loop-spacing-check.json">Unresolved spacing check</a>: current Hall entrance centres differ4.60m sideways and17.05m along the corridor. The saved26.3m Hall has aligned end doors; the present guessed room dimensions do not fit it yet.</p><h2>Current native map</h2><img src="layout.svg" alt="Eleven provisional shells with observed doorways and closed threshold ends"><ol>'+''.join('<li>'+html.escape(r['label'])+'</li>' for r in rooms)+'</ol>'
body+=f'<h2>Checks</h2><p>Native RTX {len(a["checks"])} / {len(a["checks"])} collision/camera checks; p95 {a["frame_time_p95_ms"]:.2f}ms. Chrome RTX ANGLE {len(b["engine"]["checks"])} engine checks plus actual keyboard round trip; p95 {b["engine"]["frame_time_p95_ms"]:.2f}ms, no runtime/JS errors. LightmapGI:545 surfaces; latest bake timing in checkpoint; walls still warmer than source grey. Native wide renders and browser images inspected. Black panel faces now follow their owning wall cutaway. Repository/diff checks passed. Shell44/50: four previously recorded layout/pixel failures plus two timing failures; frozen Shell unchanged. Muse new spend$0.04 sincev26, cumulative map$0.69 actual/$0.70 conservative. Heartbeat disabled, 3D Viewer untouched. Reconstruction unfinished.</p>'+pair([('grey-walk.png','Actual native camera in new grey room.'),('browser-forward.png','Chrome keyboard/camera round trip through existing European doorway.')])+'<p>Next: source-fit the full Grand Gallery loop; add missing grey-gallery sculpture, seven remaining paintings and Ionic entablature/relief using verified records and further Muse passes. Do not merge the two stair halls or invent unfilmed corridors.</p>'
style='body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto}figcaption{margin:6px 0 24px}'
(review/'index.html').write_text('<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection grey gallery v34</title><style>'+style+'</style><main>'+body+'</main></html>');shutil.copyfile(review/'index.html',e/'review.html');(share/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v34/"><a href="../architecture-review-v34/">Latest Collection reconstruction</a>');print(review)
