from pathlib import Path
from PIL import Image
import json,hashlib,subprocess,sys
app=Path('image-work/collection-room-remodel').resolve();kind=sys.argv[1]
assert not (app/f'{kind}-receipt.json').exists(),'Existing submission requires reconciliation'
specs={
'courbet-frame':(['/tmp/collection-courbet-frame-native.png','/home/reidsurmeier/risd-godot-ingestion/collection-expansion/survey-2fps/IMG_6380/000006.jpg'],'Generate ONE complete front orthographic low polygon gilded frame matching the real frame around RISD Courbet Jura Landscape43.571 in the reference views. Preserve its broad dense carved acanthus/foliate outer band with projecting corner and centre leaf ornaments, narrow raised rectangular inner gold fillet, aged warm gold and restrained relief shadows in the existing museum game style. All four sides/corners complete. Perfectly blank white rectangular opening with canvas width73.3 height59.7cm. Flat magenta #FF00FF outside silhouette; no painting, labels, walls, people, shadows outside frame, perspective or invented extra ornaments. One frame only.'),
'corot-frame':(['/tmp/collection-corot-frame-complete-native.png'],'Generate ONE complete front orthographic low polygon gilded picture frame matching RISD Corot Banks of a River24.089 in the source photo. Simple narrow rectangular frame: dark outer raised edge, flat lightly textured gold band, narrow inner raised gold lip. No broad rococo scrolls. Restrained shallow facets and aged warm gold in the museum game style. Complete all four sides/corners. Perfectly blank white inner opening, canvas46cm wide31.9cm tall. Flat magenta #FF00FF outside silhouette. No painting, other frames, walls, labels, people, perspective or shadow outside silhouette; one frame only.'),
'white-panel-door':(['/tmp/collection-white-panel-door-native.png'],'Generate ONE complete FRONT ORTHOGRAPHIC museum door leaf matching the open white door visible in reference1. Tall narrow cream-painted wooden leaf with three rectangular inset panels stacked vertically, raised stepped panel mouldings, broad flat rails and stiles, small dark metal knob/lock at mid-lower right edge. Preserve the real simple panel arrangement, not a carved ornate door. Restrained low polygon game albedo and shallow facet relief, warm off-white paint. Complete rectangular outside silhouette, all corners present. Leaf ratio height2.7m width0.95m. Flat magenta #FF00FF outside silhouette, generous margins. No jamb, surrounding architrave, wall, floor, room, glass, painting, label, people, perspective or shadows outside leaf; one door leaf only. Native closed geometry supplies thickness and panel depths.')}
sources,prompt=specs[kind];refs=[]
for i,name in enumerate(sources):
 src=Path(name);im=Image.open(src).convert('RGB')
 if src.suffix=='.jpg':im=im.rotate(270,expand=True)
 dest=app/'inventory-references'/f'{kind}-selected-{i}.png';im.save(dest);refs.append({'path':str(dest.relative_to(app)),'sha256':hashlib.sha256(dest.read_bytes()).hexdigest()})
# Shared saved Main Hall style reference.
src=app/'inventory-references/purple-plaster-selected-1.png';dest=app/'inventory-references'/f'{kind}-selected-{len(refs)}.png';dest.write_bytes(src.read_bytes());refs.append({'path':str(dest.relative_to(app)),'sha256':hashlib.sha256(dest.read_bytes()).hexdigest()})
(app/f'{kind}-prompt.txt').write_text(prompt+'\n')
plan={'attempts':[{'id':kind+'-001','prompt':kind+'-prompt.txt','promptSha256':hashlib.sha256((app/f'{kind}-prompt.txt').read_bytes()).hexdigest(),'size':'1440x1760' if kind=='white-panel-door' else '1760x1440','inputs':refs}]}
(app/f'{kind}-plan.json').write_text(json.dumps(plan,indent=2)+'\n');(app/f'{kind}-recipe.json').write_text(json.dumps({'procedure':'edit','plan':kind+'-plan.json','attempt':kind+'-001'})+'\n')
(app/f'{kind}-source.json').write_text(json.dumps({'source_video':'IMG_6380.MOV','time_seconds':3.25 if kind=='courbet-frame' else 29.25 if kind=='corot-frame' else 106.25,'role':'Video frame/moulding reference; authentic painting pixels stay official catalogue, native geometry supplies depth','source_paths':sources,'accepted':False},indent=2)+'\n')
cli=['node','/home/reidsurmeier/Image-generation-pipline/.tool-builds/1790783219515/scripts/image-pipeline.js']
r=subprocess.run(cli+['prepare','--application',str(app),'--recipe',kind+'-recipe.json','--unit-cost','0.01','--budget','0.01'],capture_output=True,text=True);assert r.returncode==0,r.stdout;(app/f'{kind}-prepared.json').write_text(r.stdout);objective=json.loads(r.stdout)['objective']
r=subprocess.run(cli+['image','--application',str(app),'--objective',objective],capture_output=True,text=True);assert r.returncode==0,r.stdout;(app/f'{kind}-planned.json').write_text(r.stdout);assert json.loads(r.stdout)['_tag']=='Planned';print(json.dumps({'kind':kind,'objective':objective}))
