# Historical initial survey writer; final hall-stairs-inventory.json includes subsequent visual corrections and six catalogue matches. Do not rerun over the final inventory.
from pathlib import Path
import json,hashlib,shutil
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');app=Path('image-work/collection-room-remodel')
rows={}
for clip,count,folder in [('IMG_6380',521,'main-hall-survey-v1'),('IMG_6381',198,'IMG_6381-survey-v1'),('IMG_6387',171,'IMG_6387-survey-v1'),('IMG_6379',365,'IMG_6379-survey-v1'),('IMG_6378',360,'IMG_6378-survey-v1')]:
 d=json.loads((root/folder/'manifest.json').read_text());assert d['frames']==count
 assert all(hashlib.sha256((root/folder/name).read_bytes()).hexdigest()==sha for name,sha in d['sheets'].items())
 d.update(reviewed=True,reviewed_at_utc='2026-10-01T03:05:00Z',sampling_note='Every extracted 2fps frame visually inspected; not every native video frame')
 (root/folder/'manifest.json').write_text(json.dumps(d,indent=2)+'\n');rows[clip]=d

def group(id,source,note,api=None):return dict(id=id,source_frames=source,observed=note,status='source-inventoried; native asset/metric fit unfinished',catalogue_match=api)
d={'date_utc':'2026-10-01','scope':'Remaining five full 2fps surveys; lower-bound inventories and filmed connections only. Collection prototype; no Viewer changes.', 'reviewed_frames':1615,'source_surveys':rows,'metric_acceptance':False,'connections':[
 {'from':'grey French gallery','to':'skylit piano stair hall upper landing','source':'6380:1-10,25-30;6379:325-365','observed':'Open double-panel door; piano hall lower level sign4 and ascending black stair visible'},
 {'from':'grey French gallery','to':'historic marble stair/fireplace hall','source':'6380:55-63,88-101,159-168;6381:38-45','observed':'Two Ionic columns and entablature; curved ascending marble stair plus separate arched descending niche'},
 {'from':'grey French gallery','to':'blue Grand Gallery','source':'6380:196-202','observed':'Large white double-panel doorway; grey gallery distinct from blue gallery'},
 {'from':'grey French gallery','to':'purple elevator-5 connector','source':'6380:196-210,480-509','observed':'Perpendicular entry beside Grand Gallery corner; modern black panels opposite purple elevator5 wall'},
 {'from':'purple connector','to':'Rockefeller','source':'6380:237-261,480-501','observed':'Opposite connector end; pale straight plank floor'},
 {'from':'dark medieval room','to':'lion-relief stair landing','source':'6387:13-30;6382:155-159','observed':'Stair door opposite Gothic doorway; blue lion relief between medieval and modern-gallery doors'},
 {'from':'lion-relief stair landing','to':'modern painting gallery','source':'6387:71-102,165-171','observed':'White French double-panel doors; source upper landing sign5'},
 {'from':'modern painting gallery','to':'adjoining light gallery, threshold only','source':'6387:121-138','observed':'Deeper opening in window wall; adjoining room not surveyed'},
 {'from':'historic marble stair upper landing','to':'warm case gallery and light case gallery, thresholds only','source':'6381:73-85,123-132','observed':'Two doors on perpendicular walls; names and connection to other filmed rooms unresolved'},
 {'from':'Metcalf Auditorium','to':'outside exit threshold only','source':'6378:337-360','observed':'Rear side ramp exit; outside room not surveyed'}],
 'unresolved_connections':['Do not merge historic marble/fireplace stair hall and skylit piano stair hall. They connect to opposite ends of the grey gallery.','Lion-relief landing may be another level/side of the skylit stair hall, but continuity is not demonstrated by these videos.','Auditorium-to-museum route not filmed. Do not invent a connecting corridor.'],
 'rooms':{
 'grey_French_gallery':{'floor':'light oak herringbone','walls':'warm grey','groups':[
 group('woodland-landscape','6380:1-10,25-30','Wooded landscape, ornate gold frame beside piano-stair door'),group('coach-landscape','6380:11-18','Coach/barn scene; purple connector left of it'),group('small-dark-cloud-landscape','6380:43-46','Small dark landscape on long wall'),group('overcast-open-landscape','6380:49-54','Larger overcast rural landscape'),group('lake-landscape','6380:57-61','Small lake/shore landscape near Ionic stair opening'),group('castle-on-hill','6380:172-177','Castle ruins atop hill with cloud foreground'),group('waterfall','6380:180-188','Waterfall between cliffs and tree'),group('colosseum','6380:190-195','Roman Colosseum/oval ruin'),group('small-corner-landscape','6380:196-202','Small landscape on pier beside Grand Gallery/purple entrances'),group('central-white-sculpture','6380:73-80,480-501','White seated female/group on low rectangular plinth; identity unresolved')],'architecture':'Two distinct stair doorways, Ionic column portal, dentil cornice, white panel doors, grey herringbone room; all extents provisional'},
 'historic_marble_stairs':{'groups':[group('mirrored-bronze-fireplace','6380:103-133;6381:1-16','Green curved firebox, paired winged bearded supports, crowned foliage and tall mirror'),group('curved-marble-stair','6381:1-37,133-198','Straight lower flight and curved winders; ornate iron balusters, wood rail, rounded newel'),group('arched-triple-window','6381:17-37,46-60','Tall arched triple window with engaged side columns and radiator grille'),group('glass-chandelier','6381:61-66,86-120','Black/blue centre with curved white glass arms, high above landing'),group('descending-niche','6380:145-156','Separate arched side niche right of fireplace; dark descending winders and rectangular sash window')],'architecture':'Upper bridge looks down through Ionic columns into grey gallery; two case-gallery thresholds above'},
 'skylit_piano_stairs':{'groups':[group('grand-piano-and-stool','6379:1-12','Black grand piano and button-upholstered black bench'),group('brown-monochrome','6379:25-42','Large plain brown rectangular work above piano end'),group('teal-polygon','6379:25-42','Large pale teal polygon near adjacent corner; precise side count/identity unresolved'),group('white-wavy-relief','6379:25-42','Intertwined white outlined square relief above lower EXIT door'),group('yellow-teal-abstract','6379:25-42','Yellow lower/teal upper densely marked abstract painting'),group('white-grid-relief','6379:25-42','White geometric grid square with green rim near upper stair')],'architecture':'Two skylights, dentil cornice, black upward bending stairs, iron balconies with wood handrail, elevator4, lower doors/ramp. Five distinct wall works, not previous four.'},
 'lion_stair_landing':{'groups':[group('blue-brick-lion','6387:1-30,71-91','Long blue/gold brick lion relief between modern and medieval doorways'),group('folding-chair-rack','6387:13-30','Black stacked folding chairs on rack; temporary equipment')],'architecture':'Upper sign5, ascending grey/white flight and descending flights, black iron rails/wood handrail, upper rectangular skylight. Exact relationship to piano stairs unverified'},
 'modern_painting_gallery':{'groups':[group('large-figurative-painting','6387:92-102,153-164','Large crowded figurative composition, left of entry'),group('pumpkin-still-life','6387:139-150','Green/orange pumpkins/apples still life, far short wall'),group('blue-yellow-village','6387:139-150','Blue/yellow rural village on far short wall'),group('cubist-still-life','6387:103-120','Cubist still life/guitar-like forms in gold frame'),group('oval-cubist-portrait','6387:103-120','Oval portrait composition within white square frame'),group('gold-figurine','6387:121-138','Standing faceted gold figure in glass case between windows'),group('central-black-bench','6387:92-102','Central black bench')],'architecture':'Pale herringbone, light walls, three multi-pane windows with white blinds and radiator/vent bases; deeper doorway on window wall'},
 'Metcalf_Auditorium':{'official_source':'https://risdmuseum.org/rent-museum','official_photo':'https://risdmuseum.org/sites/default/files/styles/scaled_1324_w/public/2018-07/page_special%20event_auditorium.jpg?itok=Fve3N1Ji','identity':'Official photograph visually matches source wood stage, ceiling beams, fixed seat backs and side double doors; official capacity200 is not a counted source seat total','groups':[group('fixed-seating','6378:1-24,80-96,123-132,207-240,310-330','Black upholstered seats, tan wood backs/armrests in tiered rows; actual count/row fit unfinished'),group('lectern','6378:169-180','Wood lectern with side shelf, laptop, microphone, AV shelf and visible cables'),group('stage-equipment','6378:193-204','Stacked blue/white chairs, wire chairs and equipment; temporary objects'),group('two-blue-chairs','6378:145-158','Two upholstered blue shell chairs at stage-side steps'),group('speakers','6378:64-78,241-253','Black angled wall speakers beside stage; upper rear equipment brackets'),group('rear-benches','6378:283-317','Black slat benches along rear wall'),group('projection-booth','6378:295-301','Wide dark booth window above rear benches; equipment visible'),group('ramp-exit','6378:337-360','Rear side ramp/metal handrails, waste bin, sign post and exit doors')],'architecture':'Light wood acoustic panels with staggered horizontal seams; grey carpet under seating/ramp, raised wood stage and five visible side steps; white ceiling beams with linear LEDs/circular lamps, black stage track fixtures, two stage-side double doors and rear exits; no gallery connection filmed'}},
 'Rockefeller_corrections':[{'source':'6380:277-281,387-408','correction':'Settee centred directly beneath Romany portrait, z=-4.7 instead of -5.2; absolute distances remain provisional'},{'source':'6380:319-348','correction':'Gold service case solid ivory pedestal to floor; pink Worcester case retains suspended tray/four legs'},{'source':'6380:367-384','remaining':'Four vertically stacked prints flanking gallery door still missing'},{'source':'6380:264-286,387-408','remaining':'Brown textile and small stool identity/placement incomplete'}],
 'official_maps':{'floor5':'https://risdmuseum.org/visitor-guide/floor-5','floor43':'https://risdmuseum.org/visitor-guide/floor-43','caution':'Primary diagrams dated2020, schematic not a measured current floor plan; support gross adjacency/level names only'}}
assert sum(v['frames'] for v in rows.values())==1615
(app/'hall-stairs-inventory.json').write_text(json.dumps(d,indent=2)+'\n')
p=app/'reconstruction-coverage.json';coverage=json.loads(p.read_text());coverage['hall_stairs_inventory']='hall-stairs-inventory.json';p.write_text(json.dumps(coverage,indent=2)+'\n')
print('Five full surveys, 1615 frames, 10 observed connections; all metrics unaccepted')
