from pathlib import Path
import json,re,shutil,urllib.request
out=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion/lowpoly-room-v43b-ceilings');public=out.parent/'review-preview';e=Path('docs/evidence/collection-reconstruction/main-worker-ceilings-20261001T0945');review=public/'architecture-review-v43';game=public/'rockefeller-architecture-v43';review.mkdir(exist_ok=False);shutil.copytree(out/'web',game)
b=json.loads((out/'evidence/browser-result.json').read_text());assert b['pass'] and b['errors']==[] and all(b['engine']['checks'].values()) and len(b['engine']['checks'])==154
proof=json.loads((out/'evidence/ceiling-visibility.json').read_text());assert all(x['authored_ceilings']==x['baked_copies']==2 for x in proof)
s=Path('/tmp/collection-v43b-shell-repeat.log').read_text();passed=len(re.findall('^PASS ',s,re.M));failed=len(re.findall('^FAIL ',s,re.M));assert passed+failed==50
for n in ['medieval-portal-wall-wide.png','renaissance-wide.png','medieval-walk.png','renaissance-walk.png','hall-wide-arch.png','loop-overview.png','medieval-frame-front.png']:shutil.copyfile(out/'evidence'/n,review/n)
for n in ['v43-dark-medieval-portal-wall-wide.png','v43-dark-renaissance-wide.png','medieval-grille-original.webp','medieval-grille-rectified-study.png','medieval-grille-review.json','v42-medieval-portal-wall-wide.png','v42-grille-88.75-review.jpg','renaissance-2.25-source.jpg','renaissance-62.25-source.jpg','architecture-review.json']:shutil.copyfile(e/n,review/n)
for n in ['browser-result.json','ceiling-visibility.json']:shutil.copyfile(out/'evidence'/n,review/n)
def fig(n,c):return f'<figure><a href="{n}"><img src="{n}" alt="{c}" loading="lazy"></a><figcaption>{c}</figcaption></figure>'
def pair(a,ac,b,bc):return '<div class="pair">'+fig(a,ac)+fig(b,bc)+'</div>'
html='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection wide-shot ceiling correction</title><style>body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto;max-height:1000px;object-fit:contain}figcaption{margin:6px 0 24px}</style><main><h1>Collection · wide-shot ceiling correction</h1><p><a href="../rockefeller-architecture-v43/">Walk the updated connected rooms</a> · <a href="../architecture-review-v42/">Previous frame and architecture comparisons</a></p><p>WASD to walk; Space resets; 2 opens the European gallery,3 the French gallery. This pass corrects the omitted flat medieval and Renaissance ceilings. Existing Muse plaster is reused on low polygon slabs, included in the native lighting bake. At eye level the ceilings are visible; above3.4m they hide with their baked copies to keep the walking camera clear. Heights3.5/4.25m are provisional.</p>'
html+=pair('v42-medieval-portal-wall-wide.png','Before: the missing room ceiling exposed the unrelated Hall skylight above the medieval portal.','medieval-portal-wall-wide.png','After: native baked eye-level wide, with a flat pale ceiling. The actual Hall remains visible through the portal. Track positions, grille, east fragment and proportions remain unfinished.')
html+=pair('v43-dark-medieval-portal-wall-wide.png','Rejected initial ceiling bake: room fill became too dark. The large fill emitters overlapped the new slabs.','medieval-portal-wall-wide.png','Revised neutral room fill, with smaller emitters below the ceilings. Brighter portal and floor; exact source lighting and fixture layout remain provisional.')
html+=pair('v42-grille-88.75-review.jpg','IMG_6382 88.75s: flat ceiling, multiple tracks and spotlights; iron grille right of the portal and a stone fragment near the stair door.','medieval-walk.png','Actual elevated walking camera: ceiling cutaway keeps the visitor and route visible. This is presentation proof, not source geometry acceptance.')
html+=pair('renaissance-62.25-source.jpg','IMG_6383 62.25s: pale flat ceiling and track lighting over the bench, shutters, display cases and European doorway.','renaissance-wide.png','Current native baked reciprocal wide: flat ceiling retained; source objects and precise layout still incomplete.')
html+=pair('renaissance-2.25-source.jpg','IMG_6383 2.25s looking through tracery toward the medieval portal: reciprocal room connection visible.','renaissance-walk.png','Elevated Renaissance walking camera remains open after the ceiling correction.')
html+=pair('medieval-frame-front.png','Previously fitted Muse Magdalene frame and separate authentic painted panel retained.','hall-wide-arch.png','Existing Main Hall presentation and23 verified paintings retained.')
html+=pair('medieval-grille-rectified-study.png','Source grille plane, manually straightened for inspection only; aspect and metres unverified. Seven scroll columns observed.','medieval-grille-original.webp','Single Muse trial,$0.01: eight columns and other pattern differences. Rejected for direct installation, retained for material/shape fitting; not an accepted museum asset.')
html+=fig('loop-overview.png','Connected room circuit overview with ceilings hidden. Room metres and placement are provisional; this is not a verified full museum map.')
html+=f'<p>RTX4070SUPER Chrome154/154 checks and real keyboard round trip,errors[],p95{b["engine"]["frame_time_p95_ms"]:.2f}ms.801 native baked surfaces; eye-level/elevated assertions verify both authored ceilings and baked copies. Owning Shell{passed}/50,{failed} failures retained. scripts/check.sh and git diff --check pass. No new native performance claim;60fps target is unresolved.</p><p>Existing Muse plaster reused. One$0.01 OpenRouter Muse grille pass: source7 columns vs generated8, rejected for direct installation; no blind retry. Cumulative$0.75 actual/$0.76 conservative. Heartbeat disabled; sole main worker. Full reconstruction remains unfinished: source-fitted room/door/object positions, tracks and lighting, remaining sculpture/case contents, stairs, auditorium and modern gallery. Next refine medieval grille/east-wall/stair assets and widen reciprocal placement checks.</p><p><a href="ceiling-visibility.json">Camera/ceiling checks</a> · <a href="architecture-review.json">Source findings and uncertainties</a> · <a href="browser-result.json">Browser report</a></p></main></html>'
(review/'index.html').write_text(html);(e/'review.html').write_text(html)
(public/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v43/"><a href="../architecture-review-v43/">Latest Collection reconstruction</a>')
base='https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'
for n in ['architecture-review-v43/','architecture-review-v43/medieval-portal-wall-wide.png','rockefeller-architecture-v43/','rockefeller-architecture-v43/index.pck']:
 with urllib.request.urlopen(base+n,timeout=30) as r:assert r.status==200
print('Published',base+'progress/')
