from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil,subprocess,tarfile,re
app=Path('image-work/collection-room-remodel');e=Path('docs/evidence/collection-reconstruction/main-worker-ceilings-20261001T0945');out=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion/lowpoly-room-v43b-ceilings')
b=json.loads((out/'evidence/browser-result.json').read_text());assert b['pass'] and b['errors']==[] and len(b['engine']['checks'])==154 and all(b['engine']['checks'].values()) and 'NVIDIA' in b['webgl_renderer']
loop=[x for x in b['engine']['samples'] if x['trial'].startswith('loop_')];assert len(loop)==33 and all(x['started_without_reset'] for x in loop[1:])
proof=json.loads((out/'evidence/ceiling-visibility.json').read_text());assert len(proof)==2 and all(x['authored_ceilings']==x['baked_copies']==2 for x in proof);assert proof[0]['visible'] and not proof[1]['visible']
shell=Path('/tmp/collection-v43b-shell-repeat.log').read_text();passed=len(re.findall(r'^PASS ',shell,re.M));failed=len(re.findall(r'^FAIL ',shell,re.M));assert passed+failed==50
assert 'checks passed' in Path('/tmp/collection-v43b-check.log').read_text();assert 'BAKE_OK users=801' in Path('/tmp/collection-v43b-bake.log').read_text();assert '[editor_plugins]' not in (out/'project.godot').read_text()
assert 'REMODEL_VISUAL_PROOF' in Path('/tmp/collection-v43b-visual.log').read_text();assert 'SCRIPT ERROR' not in Path('/tmp/collection-v43b-visual.log').read_text()
m=json.loads((out/'manifest.json').read_text())
for p,h in m['source_sha256'].items():assert hashlib.sha256(Path(p).read_bytes()).hexdigest()==h,p
r=json.loads((app/'reconstruction-coverage.json').read_text());r['current_preview']='https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/architecture-review-v43/';r['room_ceilings']={'sources':['IMG_6383 2.25/62.25s','IMG_6382 88.75s'],'omitted_ceiling_fixed':True,'authored_ceilings':2,'baked_copies':2,'height_m':{'Renaissance':3.5,'medieval':4.25},'metric_accepted':False,'track_layout_accepted':False,'native_eye_and_elevated_views_inspected':True,'browser_checks_passed':154,'browser_errors':[],'browser_frame_time_p95_ms':b['engine']['frame_time_p95_ms'],'baked_surfaces':801,'shell_passed':passed,'shell_total':50,'next':'Source-fit medieval grille/east-wall fragment/stair door and lighting tracks; continue reciprocal wide placement and all-room reconstruction.'};r['medieval_panels']['next']=r['room_ceilings']['next'];r['medieval_panels']['cumulative_map_actual_usd']='0.75';r['medieval_panels']['cumulative_map_conservative_usd']='0.76';r['medieval_grille_trial']=json.loads((app/'medieval-grille-review.json').read_text());(app/'reconstruction-coverage.json').write_text(json.dumps(r,indent=2)+'\n')
a=json.loads((e/'architecture-review.json').read_text());a['presentation_checks']='Native baked eye-level and elevated views inspected. Assertions verify two authored slabs and both baked copies visible at1.65m and hidden at5.3m; browser154/154 plus keyboard round trip.';a['omitted_ceiling_fixed']=True;a['paid_calls']=1;a['muse_grille_trial']=json.loads((app/'medieval-grille-review.json').read_text());a['lighting_final']='Final native eye-level/actual walking views inspected: brighter neutral room fill after shrinking emitter and tuning energy. Source lighting, fixture placement/count and room heights remain provisional.';(e/'architecture-review.json').write_text(json.dumps(a,indent=2)+'\n')
for n in ['manifest.json','geometry.json']:shutil.copyfile(out/n,e/n)
shutil.copyfile(app/'reconstruction-coverage.json',e/'reconstruction-coverage.json')
for n in ['ceiling-visibility.json','browser-result.json','medieval-portal-wall-wide.png','renaissance-wide.png','medieval-walk.png','renaissance-walk.png','hall-wide-arch.png','loop-overview.png','medieval-frame-front.png','browser-forward.png','browser-reverse.png']:shutil.copyfile(out/'evidence'/n,e/n)
for n in ['collection-v43b-final-checks.py','collection-v43b-browser-with-server.py','collection-v41-bake.py','collection-publish-v43.py']:shutil.copyfile('/tmp/'+n,e/n)
logs=list(Path('/tmp').glob('collection-v43*.log'))
with tarfile.open(e/'raw-checks-and-shell-film.tar.gz','w:gz') as a:
 for p in logs:a.add(p,arcname=p.name)
 a.add('/tmp/collection-v43b-shell-repeat',arcname='owning-shell-final')
 a.add('/tmp/collection-v43-shell-repeat',arcname='owning-shell-initial-lighting-trial')
for p in logs:(e/p.name).write_text('\n'.join(x.rstrip() for x in p.read_text().splitlines()).rstrip()+'\n')
entry=f'''\n### Collection v43 — source-observed flat room ceilings (2026-10-01)\n\nIMG_6382 88.75s and new native CUDA-decoded6383 2.25/38.25/62.25s inspected. Source medieval/Renaissance ceilings are flat pale plaster with track spots. The deliberate omission of opaque ceilings exposed the unrelated Hall skylight at eye height. Two native low polygon slabs now reuse existing Muse neutral-plaster texture and presentation material;3.5/4.25m heights remain provisional. Existing ceiling visibility hides slabs above3.4m and keeps them visible during bake preparation. Native assertion verifies both authored meshes and their baked copies visible at1.65m, hidden at5.3m. Eye-level and actual elevated walking views inspected; track count/positions, room/door/object metrics, case contents and remaining architecture remain incomplete. Main Hall23 paintings retained; Viewer/frozen seams untouched.\n\nInitial ceiling bake too dark compared with source;2.5m room fill emitters overlap the slabs. Final enclosed-room fill uses.12m emitter with positive clearance assertion and neutral energy1.1; exact track/spot positions remain provisional.801 native surfaces baked with the existing CPU Vulkan fallback and renderer configuration restored; RTX4070SUPER native visual review and Chrome154/154 plus real keyboard round trip,33 continuous circuit segments,p95{b['engine']['frame_time_p95_ms']:.3f}ms,errors[]. Owning Shell final{passed}/50,{failed} failures; initial lighting trial44/50 included two recurring animation timing failures. Both full films and exact raw logs retained. Repository checks and git diff --check pass. No new native performance claim;60fps target unresolved. All{len(m['source_sha256'])} prepared source hashes and50 original pending hashes match. One OpenRouter meta/muse-image grille run6d9f3b3e3a4b26e3c758f21c,$0.01,immutable original/hash/receipt/reservation archived. Source7 columns vs generated8: rejected direct installation; row count,handedness,missing curl and spacing unverified. No blind retry. Total64 outputs plus prior$0.11:$0.75 actual/$0.76 conservative. Existing Muse plaster reused. Exact native source frames/hash manifest retained in ingestion;540x960 JPEG review derivatives in evidence.\n\nFull reconstruction remains unfinished. Next fit medieval grille, east-wall stone fragment, stair door and track lighting from reciprocal wide shots, then remaining rooms/objects/case contents. Grille catalogue identity unmatched; do not substitute rejected27.184 or clock53.085. Failed headv1/v2 remain unaccepted. Sole main worker, heartbeat disabled. No production integration or ticket closure. Evidence `{e}/`.\n'''
Path('/tmp/collection-provenance-ceilings-entry.md').write_text(entry);p=Path('modules/shell/PROVENANCE.md');assert not p.read_text().endswith(entry);p.write_text(p.read_text()+entry)
Path('/tmp/collection-v43b-staged-provenance.md').write_bytes(subprocess.check_output(['git','show','HEAD:modules/shell/PROVENANCE.md'])+entry.encode())
s=p.read_bytes()
for n in ['ceilings','gabled','panels','loop','perugino','bertin','cases','european-door','wide-scale','ionic','grey','full-survey','sculpture-layout','gallery','wide','inventory']:
 q=Path('/tmp/collection-provenance-'+n+'-entry.md').read_bytes();assert s.endswith(q),n;s=s[:-len(q)]
d=json.loads(Path('/tmp/collection-inventory-pending-before.json').read_text())
for path,h in d.items():assert hashlib.sha256(s if path=='modules/shell/PROVENANCE.md' else Path(path).read_bytes()).hexdigest()==h,path
(e/'preservation.json').write_text(json.dumps({'original_pending_files':len(d),'all_original_hashes_match':True,'prepared_source_count':len(m['source_sha256']),'all_source_hashes_match':True,'provenance_method':'Strip only16 session-authored entries; preserve original21 pending lines unstaged'},indent=2)+'\n')
failures='\n'.join(x.rstrip() for x in re.findall(r'^FAIL .*',shell,re.M));now=datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
(e/'CHECKPOINT.md').write_text(f'''# Collection checkpoint — {now}

Prototype v43. Sole main worker, heartbeat disabled. Goal active and unfinished. Viewer/frozen seams untouched; no production integration or ticket closure.

1. Wide native6382 88.75s and6383 2.25/62.25s show flat pale ceilings with track spots. Corrected missing opaque medieval/Renaissance ceilings that exposed Hall skylight. Two native slabs reuse existing Muse plaster; room heights3.5/4.25m remain provisional, track layout/lighting still wrong. Eye-level baked and actual elevated walking views inspected. Assertions verify both authored and both baked meshes visible at1.65m and hidden at5.3m. Bake preparation retains all801 surfaces. Existing Hall23 paintings and authentic separate panel/frame retained.
2. Initial opaque-ceiling bake too dark and retained as rejected lighting trial. Enclosed-room neutral fill emitter reduced2.5m to.12m with clearance assertion,energy1.1; brightness improved only as judged in final views, not an accepted photometric match. RTX Chrome154/154 plus real keyboard round trip,33 continuous circuit segments,p95{b['engine']['frame_time_p95_ms']:.3f}ms,ready{b['first_ready_ms']}ms,errors[]. Native bake CPU Vulkan fallback; configuration restored. No new native performance claim;60fps/cold remote target unresolved. Owning Shell final{passed}/50,{failed} failures; initial lighting trial44/50 included two recurring animation timing failures. Both full films/exact raw logs archived. scripts/check.sh/git diff --check pass. All{len(m['source_sha256'])} source hashes and50 original pending hashes match.
3. One Muse grille request through OpenRouter,$0.01,source7 columns versus generated8: rejected direct installation. Source row count/handedness/missing curl/spacing unverified; fit from existing sheet and source guide before any retry. Immutable original,receipt and full reservation/run archived. Total$0.75 actual/$0.76 conservative; existing Muse plaster reused. Source1080x1920 frames retained in ingestion with video/frame hashes and CUDA decode commands;540x960 review JPEGs are derivatives. Failed headv1/v2 and ambiguous river-deities unchanged.
4. Next fit medieval grille right of portal, east-wall stone fragment/stair doorway, track spots and reciprocal wide object/door layout. Grille still unmatched;27.184 and clock53.085 are not established matches. Tracery inner-edge UVs stretch into striped bands at oblique angles; preserve the finding and correct during the next architecture asset pass. Continue all remaining room contents,stairs,auditorium and modern gallery; full measured map unfinished. No external blocker.

Owning Shell failures:

{failures}

https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/progress/

Reproduce: prepare_remodel.py fresh output; saved native bake helper with Mobile scene priming; RTX remodel_review.gd; Web export/browser wrapper; owning Shell. Exact logs archived; readable copies trim trailing whitespace. All map/tickets remain open under their original scope.
''')
shutil.copyfile(__file__,e/'finish-checkpoint.py')
for n in ['remodel_room.gd','remodel_review.gd','remodel_bake.gd']:shutil.copyfile(Path('modules/shell/prototype/collection_reconstruction')/n,e/n)
hashes={str(p.relative_to(e)):hashlib.sha256(p.read_bytes()).hexdigest() for p in e.rglob('*') if p.is_file() and p.name!='SHA256.json'};(e/'SHA256.json').write_text(json.dumps(hashes,indent=2)+'\n')
print('Evidence',len(hashes),'files; Shell',passed,'/50; pending preserved')
