from pathlib import Path
import json,re,shutil,urllib.request,hashlib
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v47c-lion-plaster';public=root/'review-preview';e=Path('docs/evidence/collection-reconstruction/main-worker-lion-plaster-20261001T1220');review=public/'architecture-review-v47';game=public/'rockefeller-architecture-v47'
b=json.loads((e/'browser-result.json').read_text());assert b['pass'] and not b['errors'] and len(b['engine']['checks'])==174
review.mkdir(exist_ok=False);shutil.copytree(out/'web',game)
for p in e.iterdir():
 if p.suffix in ['.png','.jpg','.webp','.json']:shutil.copyfile(p,review/p.name)
def fig(n,c):return f'<figure><a href="{n}"><img src="{n}" alt="{c}" loading="lazy"></a><figcaption>{c}</figcaption></figure>'
def pair(a,ac,z,zc):return '<div class="pair">'+fig(a,ac)+fig(z,zc)+'</div>'
h='''<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection · lion landing and architecture</title><style>body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto;max-height:900px;object-fit:contain}figcaption{margin:6px 0 24px}</style><main><h1>Collection · lion landing and architecture</h1><p><a href="../rockefeller-architecture-v47/">Walk the updated rooms</a> · <a href="../architecture-review-v46/">Previous pass</a></p><p>WASD to walk; Space resets; 2 European gallery, 3 French gallery, 4 modern gallery, 5 stair landing. Wide-angle review now places the lion beside the modern doorway. New Muse wall plaster, vent and mounting studies, and softer modern lighting are installed. Main Hall presentation retained.</p><p>Room and object offsets remain provisional. Stairs need their filmed curve, rails and destinations; the landing roof around the stair opening is missing. Individual lion brick relief is unfinished. The large modern painting, gold seated sculpture/case, chair rack, adjoining room interiors and other missing rooms/objects remain to be completed.</p>'''
for row in [('wide-42.25-source.jpg','Video source: doorway, lion edge, pale mount and overhead vent.','landing-lion-wide.png','Latest native wide: lion between modern doorway and adjacent wall opening; exact offsets still provisional.'),('striding-lion-zoom-0.jpg','Official RISD Panel with Striding Lion34.652.','landing-lion-front.png','Original museum front preserved at catalogue width/height; individual brick relief unfinished.'),('lion-panel-original.webp','Muse trial changed aspect and damaged brick details; rejected for the visible front.','landing-lion-oblique.png','Closed low polygon slab uses official front and inferred Muse side/back colour; depth unmeasured.'),('v47b-lion-floating-before-fix.png','Earlier native trial caught a catalogue group offset that left the lion floating.','landing-lion-wide.png','Corrected against the actual drawn node position; side mounting depth remains provisional.'),('landing-plaster-video-native.png','Wide-angle footage used as the plaster reference.','landing-plaster-original.webp','New Muse quiet matte plaster study; exact source colour remains unaccepted.'),('v46-modern-entry-wide.png','Previous modern gallery had pronounced painting spotlight pools.','modern-entry-wide.png','Current bake: softer lighting and new plaster; artwork ordering retained.'),('modern-windows-wide.png','Modern window-wall and deeper doorway studies.','modern-walk.png','Actual walking view; dedicated Matisse/Villon frames and missing objects remain.'),('landing-stair-void.png','Physical stair opening; curved flights and roof still unfinished.','hall-wide-arch.png','Existing Main Hall presentation retained.')]:h+=pair(*row)
h+=f'''<p>1,486 native surfaces baked; 174/174 browser navigation/camera checks plus keyboard walking, errors[]. Frame p95{b['engine']['frame_time_p95_ms']:.2f}ms; 60fps remains unverified. Owning Shell46/50 with four existing failures retained. Repository/source/hash checks pass.</p><p>Two OpenRouter Muse outputs, $0.02 this pass; cumulative $0.81 actual/$0.82 conservative. Lion trial was rejected for aspect/damage changes; official front protected. Full reconstruction unfinished. Heartbeat disabled; sole main worker continues.</p><p><a href="browser-result.json">Browser checks</a> · <a href="lion-source-proof.json">Source and placement proof</a> · <a href="lion-panel-review.json">Muse lion review</a> · <a href="https://risdmuseum.org/art-design/collection/panel-striding-lion-34652">RISD lion record</a></p></main></html>'''
(review/'index.html').write_text(h);(e/'review.html').write_text(h)
base='https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'
for n in ['architecture-review-v47/','architecture-review-v47/landing-lion-wide.png','rockefeller-architecture-v47/','rockefeller-architecture-v47/index.pck']:
 with urllib.request.urlopen(base+n,timeout=30) as response:assert response.status==200
(public/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v47/"><a href="../architecture-review-v47/">Latest Collection reconstruction</a>')
(e/'SHA256.json').write_text(json.dumps({str(p.relative_to(e)):hashlib.sha256(p.read_bytes()).hexdigest() for p in e.rglob('*') if p.is_file() and p.name!='SHA256.json'},indent=2)+'\n');print('Published',base+'progress/')
