from pathlib import Path
import json,re,shutil,urllib.request,hashlib
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v46d-landing-modern';public=root/'review-preview';e=Path('docs/evidence/collection-reconstruction/main-worker-connected-modern-20261001T1135');review=public/'architecture-review-v46';game=public/'rockefeller-architecture-v46'
b=json.loads((e/'browser-result.json').read_text());assert b['pass'] and not b['errors'] and len(b['engine']['checks'])==174
review.mkdir(exist_ok=False);shutil.copytree(out/'web',game)
for p in e.iterdir():
 if p.suffix in ['.png','.jpg','.webp','.json']:shutil.copyfile(p,review/p.name)
def fig(n,c):return f'<figure><a href="{n}"><img src="{n}" alt="{c}" loading="lazy"></a><figcaption>{c}</figcaption></figure>'
def pair(a,ac,z,zc):return '<div class="pair">'+fig(a,ac)+fig(z,zc)+'</div>'
h='''<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection · connected landing and modern gallery</title><style>body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto;max-height:1000px;object-fit:contain}figcaption{margin:6px 0 24px}</style><main><h1>Collection · landing and modern gallery</h1><p><a href="../rockefeller-architecture-v46/">Walk the updated rooms</a> · <a href="../architecture-review-v45/">Previous pass</a></p><p>WASD to walk; Space resets; 2 European gallery, 3 French gallery, 4 modern gallery, 5 stair landing. Reciprocal wide-angle video review corrected the room handedness: entry/large painting wall west, windows east, Braque/Villon beside entry and Matisse/Cézanne on the far wall. Three landing doors are distinct. Museum art uses official photographs; new Muse passes supplied two frames. Main Hall presentation retained. Full reconstruction remains unfinished.</p><p>Room dimensions and object offsets remain provisional. The large figurative painting, seated gold sculpture, lion relief and chair rack are missing here. Modern painting spotlight pools are too bright against source and still need refinement. Stairs are initial straight studies: source curves, rail details and destinations remain unfinished. White sculpture-room and deeper gallery are thresholds only.</p>'''
for row in [('landing-wide.jpg','Source reciprocal landing wide: three doors, stairs, lion relief and temporary chair rack.','landing-modern-door.png','Current landing: opposite modern door retained; lion and chair rack still missing.'),('v45-capped-stair-door.png','Previous medieval stair doorway stopped at a plain cap.','medieval-stair-wall-wide.png','Current doorway connects into the landing; stone studies remain unaccepted for damage fidelity.'),('landing-wide.jpg','Source floor, stair edges and rail ordering.','landing-stair-void.png','Actual floor opening and two provisional ramp/tread studies; curve and exact dimensions unfinished.'),('modern-wide.jpg','Video modern-room wide: bench, three windows and artwork ordering.','modern-entry-wide.png','Corrected native wide: window wall on the right, Matisse/Cézanne far ahead. Large left-wall painting still missing.'),('modern-far-wall-sequence.jpg','Far-wall video sequence used to check order and identity.','modern-windows-wide.png','Native window, blind, radiator-base and deeper-door studies; exact source construction unaccepted.'),('braque-still-life-official.jpg','Official RISD Braque Still Life 48.248.','modern-braque.png','Original art with new Muse cream/gold frame. Band widths, profile and placement provisional.'),('villon-head-woman-official.jpg','Official RISD Villon Head of a Woman 70.058.','modern-villon.png','Oval original study in provisional white frame; dedicated frame pass remains.'),('matisse-green-pumpkin-official.jpg','Official RISD Matisse The Green Pumpkin 57.037. Previous 41.012 six-apple match was wrong and is retracted.','modern-pumpkin.png','Source pumpkin identity corrected. Original art installed; reused Braque frame remains unaccepted.'),('cezanne-banks-river-official.jpg','Official RISD Cézanne On the Banks of a River 43.255.','modern-cezanne.png','Original art with new Muse grey-bronze frame. Source right edge clipped; symmetric restoration inferred. Fine ornament unaccepted.'),('seated-woman-duchamp-villon-official.jpg','Official Raymond Duchamp-Villon Seated Woman67.089: matches the gold sculpture in video. Asset/case still missing.','modern-wide.jpg','Video64.25/66.25s: tilted faceless head, diagonal arm, interlocking knees and rectangular gold base match; ready for a source-preserving Muse pass.'),('modern-walk.png','Actual walking presentation and ceiling cutaway.','hall-wide-arch.png','Existing Main Hall lighting, 23 paintings and visitor retained.')]:h+=pair(*row)
s=Path('/tmp/collection-v46d-shell-repeat.log').read_text();passed=len(re.findall('^PASS ',s,re.M));failed=len(re.findall('^FAIL ',s,re.M))
h+=f'''<p>1472 native surfaces baked with CPU Vulkan fallback. RTX4070SUPER Chrome174/174 navigation/camera checks, including eight new door/bench/guard trials, 33 continuous circuit segments and keyboard round trip; p95{b['engine']['frame_time_p95_ms']:.2f}ms, errors[]. Three ceiling copies follow cutaway. Owning Shell{passed}/50, {failed} failures retained. Repository and source/hash checks pass. Full stair traversal and native60fps target remain unverified.</p><p>Two OpenRouter Muse frame outputs, $0.02 this pass; originals, references, receipts and reservations retained. Cumulative $0.79 actual/$0.80 conservative. Heartbeat disabled; sole main worker. Next: source-preserving lion relief, remaining modern-room objects and dedicated frames, then curved stairs and room/object offsets. No full-map completion claim.</p><p><a href="browser-result.json">Browser checks</a> · <a href="layout-source-proof.json">Layout and source proof</a> · <a href="braque-frame-review.json">Braque frame review</a> · <a href="cezanne-frame-review.json">Cézanne frame review</a> · <a href="https://risdmuseum.org/art-design/collection/green-pumpkin-57037">RISD Matisse</a> · <a href="https://risdmuseum.org/art-design/collection/banks-river-au-bord-dune-riviere-43255">RISD Cézanne</a></p></main></html>'''
(review/'index.html').write_text(h);(e/'review.html').write_text(h)
base='https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'
for n in ['architecture-review-v46/','architecture-review-v46/modern-entry-wide.png','rockefeller-architecture-v46/','rockefeller-architecture-v46/index.pck']:
 with urllib.request.urlopen(base+n,timeout=30) as response:assert response.status==200
(public/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v46/"><a href="../architecture-review-v46/">Latest Collection reconstruction</a>')
(e/'SHA256.json').write_text(json.dumps({str(p.relative_to(e)):hashlib.sha256(p.read_bytes()).hexdigest() for p in e.rglob('*') if p.is_file() and p.name!='SHA256.json'},indent=2)+'\n');print('Published',base+'progress/')
