from pathlib import Path
import json,re,shutil,urllib.request,hashlib
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v45b-stair-wall';public=root/'review-preview';e=Path('docs/evidence/collection-reconstruction/main-worker-stair-wall-20261001T1100');review=public/'architecture-review-v45';game=public/'rockefeller-architecture-v45';review.mkdir(exist_ok=False);shutil.copytree(out/'web',game)
b=json.loads((e/'browser-result.json').read_text());assert b['pass'] and b['errors']==[] and len(b['engine']['checks'])==158
s=Path('/tmp/collection-v45b-shell-repeat.log').read_text();passed=len(re.findall('^PASS ',s,re.M));failed=len(re.findall('^FAIL ',s,re.M))
names=['stair-20.75-source.jpg','stair-17.25-source.jpg','stair-26.25-source.jpg','stair-77.75-source.jpg','stair-78.75-source.jpg','medieval-stair-wall-wide.png','medieval-stair-door-detail.png','medieval-apostle-left.png','medieval-apostle-right.png','medieval-portal-wall-wide.png','medieval-walk.png','hall-wide-arch.png','v44-medieval-wide.png','v45-stretched-sides-unbaked.png','apostle-41046-zoom-0.jpg','apostle-41045-zoom-0.jpg','apostle-41046-original.webp','apostle-41045-original.webp','apostle-41046-review.json','apostle-41045-review.json','apostle-mesh-proof.json','browser-result.json','collection-v45-modern-wide.jpg','collection-v45-IMG_6387-east-wide.jpg','villon-head-video.jpg','villon-head-official.jpg']
for n in names:shutil.copyfile(e/n,review/n)
def fig(n,c):return f'<figure><a href="{n}"><img src="{n}" alt="{c}" loading="lazy"></a><figcaption>{c}</figcaption></figure>'
def pair(a,ac,b,bc):return '<div class="pair">'+fig(a,ac)+fig(b,bc)+'</div>'
html='''<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection · medieval stair-wall group</title><style>body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto;max-height:1000px;object-fit:contain}figcaption{margin:6px 0 24px}</style><main><h1>Collection · medieval stair-wall group</h1><p><a href="../rockefeller-architecture-v45/">Walk the updated rooms</a> · <a href="../architecture-review-v44/">Previous grille pass</a></p><p>WASD to walk; Space resets;2 opens the European gallery,3 the French gallery. Added the two stone figures beside the stair door, their brackets/backplates, open double leaves and black door hardware. RISD photographs match Apostle41.046 on the left and41.045 on the right. Their catalogue width/height supplies scale. Exact placement, depth and room dimensions are provisional. Both Muse sculpture passes alter surviving damage and remain unaccepted; these are preliminary shape/style studies. The actual stair landing beyond the door is still a capped threshold. Full reconstruction remains unfinished.</p>'''
html+=pair('stair-77.75-source.jpg','Source wide: portal and grille at left, Apostles beside the stair door, tall case in front. The source stair landing and remaining right-wall sculptures are not complete in the model.','medieval-stair-wall-wide.png','Current baked wide: left/right bracket group and open door hardware added. Case contents, room proportions, source lighting and real stair view remain unfinished.')
html+=pair('v44-medieval-wide.png','Previous pass: grille present, stair-wall sculptures and door leaves missing.','medieval-stair-door-detail.png','Current door group: two open leaves,black push bars,hinges and closers,green EXIT. Existing Muse ivory panel textures reused; leaf dimensions/swing/panel details provisional.')
html+=pair('stair-20.75-source.jpg','Native20.75s: door leaves open into the bright stair landing, with push bars and closers.','medieval-stair-door-detail.png','Native baked door detail. The plain wall beyond remains a temporary threshold cap, not reconstructed stairs.')
html+=pair('apostle-41046-zoom-0.jpg','Official RISD Apostle41.046: turned head, diagonal arm, damaged robe and irregular broken slab. Catalogue82.6×26.7cm height/width.','medieval-apostle-left.png','Left Muse/native study: source identity/side matched, catalogue size used. Generation repairs eroded facial/robe detail; not accepted as a faithful sculpture.')
html+=pair('apostle-41045-zoom-0.jpg','Official RISD Apostle41.045: missing face, crossed hands, worn collar/folds and broken cavity above feet. Catalogue86.4×25.4cm height/width.','medieval-apostle-right.png','Right Muse/native study: generation invents a projecting head fragment and cleans surviving ornament despite the damage-preservation prompt. Unaccepted; no blind retry.')
html+=pair('v45-stretched-sides-unbaked.png','Initial native study: repeated frontal UVs stretch face/robe colours into bands on slab sides.','medieval-stair-door-detail.png','Side UVs corrected to plain stone colour from the same Muse image. Native relief remains a simplified closed slab; nominal12cm depth and profile provisional.')
html+=pair('medieval-walk.png','Actual elevated walking camera retains ceiling cutaway and connected routes. The source camera is eye height; this is presentation proof.','hall-wide-arch.png','Existing Main Hall presentation,lighting,23 paintings and visitor retained.')
html+=pair('collection-v45-IMG_6387-east-wide.jpg','Reciprocal6387 source: lion landing has three distinct doors,ascending/descending stair flights and temporary chair rack. Not built yet.','collection-v45-modern-wide.jpg','Next room constraints from6387: straight boards,bench,three windows,separate window-wall opening and ordered painting/sculpture groups. Room not built yet.')
html+=pair('villon-head-video.jpg','6387 frame113, rotated clockwise: oval portrait beside Braque, white square frame.','villon-head-official.jpg','Official RISD Jacques Villon, Head of a Woman70.058,54.8×46cm. Distinct face planes/background match; identity verified, native asset and modern room placement still unfinished.')
html+=f'''<p>900 native surfaces baked with CPU Vulkan fallback. RTX4070SUPER Chrome158/158 navigation/camera checks plus real keyboard round trip and33 continuous circuit segments,p95{b['engine']['frame_time_p95_ms']:.2f}ms,errors[]. Each prepared relief mesh has162 vertices,320triangles and480opposite paired edges with positive volume; that check proves closure only. Owning Shell{passed}/50,{failed} existing failures retained. Repository/diff checks pass. No new native performance claim;60fps target unresolved.</p><p>Two OpenRouter Muse outputs,$0.02 this pass; native originals/receipts/reservations/source hashes retained. Both fail complete damage fidelity and remain unaccepted. Cumulative$0.77 actual/$0.78 conservative. Heartbeat disabled; sole main worker. Next build source-constrained lion landing/modern-room connections and refine room/door/object placement,remaining contents and track lighting. No invented connector to piano stairs or auditorium.</p><p><a href="apostle-41046-review.json">Left Muse review</a> · <a href="apostle-41045-review.json">Right Muse review</a> · <a href="apostle-mesh-proof.json">Prepared mesh closure/UV proof</a> · <a href="browser-result.json">Browser report</a></p></main></html>'''
(review/'index.html').write_text(html);(e/'review.html').write_text(html)
base='https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'
for n in ['architecture-review-v45/','architecture-review-v45/medieval-stair-wall-wide.png','rockefeller-architecture-v45/','rockefeller-architecture-v45/index.pck']:
 with urllib.request.urlopen(base+n,timeout=30) as r:assert r.status==200
(public/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v45/"><a href="../architecture-review-v45/">Latest Collection reconstruction</a>')
(e/'SHA256.json').write_text(json.dumps({str(p.relative_to(e)):hashlib.sha256(p.read_bytes()).hexdigest() for p in e.rglob('*') if p.is_file() and p.name!='SHA256.json'},indent=2)+'\n');print('Published',base+'progress/')
