from pathlib import Path
import json,shutil,re,urllib.request
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v42b-gabled';public=root/'review-preview';e=Path('docs/evidence/collection-reconstruction/main-worker-gabled-frame-20261001T0925');app=Path('image-work/collection-room-remodel')
b=json.loads((out/'evidence/browser-result.json').read_text());assert b['pass'] and b['errors']==[] and all(b['engine']['checks'].values()) and len(b['engine']['checks'])==154
shell=Path('/tmp/collection-v42b-shell-repeat.log').read_text();passed=len(re.findall(r'^PASS ',shell,re.M));failed=len(re.findall(r'^FAIL ',shell,re.M));assert passed+failed==50
review=public/'architecture-review-v42';game=public/'rockefeller-architecture-v42';review.mkdir(exist_ok=False);shutil.copytree(out/'web',game)
for n in ['medieval-frame-front.png','medieval-frame-oblique.png','medieval-panel-magdalene.png','medieval-north-panel-wide.png','medieval-portal-wall-wide.png','hall-wide-arch.png','loop-overview.png']:shutil.copyfile(out/'evidence'/n,review/n)
for n in ['magdalene-frame-fitted.png','magdalene-painting-original-crop.png','grille-12.25-review.jpg','grille-88.75-review.jpg','architecture-review.json']:shutil.copyfile(e/n,review/n)
old=public/'architecture-review-v41'
for n in ['panel-72.75.png','panel-85.75.png','magdalene-frame-v2b-original.webp']:shutil.copyfile(old/n,review/n)
for p,name in [(out/'evidence/browser-result.json','browser-result.json'),(out/'evidence/magdalene-frame-native.json','native-geometry.json'),(app/'magdalene-frame-source-fit.json','source-fit.json'),(out/'geometry.json','geometry.json')]:shutil.copyfile(p,review/name)
def fig(n,c):return f'<figure><a href="{n}"><img src="{n}" alt="{c}" loading="lazy"></a><figcaption>{c}</figcaption></figure>'
def pair(a,ac,b,bc):return '<div class="pair">'+fig(a,ac)+fig(b,bc)+'</div>'
html='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection source-shaped gabled frame</title><style>body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto;max-height:1000px;object-fit:contain}figcaption{margin:6px 0 24px}</style><main><h1>Collection · source-shaped medieval frame</h1><p><a href="../rockefeller-architecture-v42/">Walk the current connected rooms</a> · <a href="../architecture-review-v41/">Previous source comparisons and rejected generation</a></p><p>WASD to walk; Space resets; 2 opens the European gallery view,3 the French gallery. Mary Magdalene21.250 is now installed between the curved Virgin panel and Saint Peter, following their source wall grouping. The corrected Muse gold is fitted to the museum photograph rather than leaving the wider generated opening.</p>'
html+=pair('panel-72.75.png','Original video detail: Lippo Memmi Mary Magdalene21.250.','medieval-frame-front.png','Current native baked close view. Original painting stays separate from the fitted Muse carved frame. Depth and exact mounting position remain provisional.')
html+=pair('magdalene-frame-v2b-original.webp','Unchanged corrected Muse output from the previous pass. Its opening needed proportion fitting.','magdalene-frame-fitted.png','Source-shaped texture derivative: outer outline and painted opening follow the museum photograph; native gold bands fitted to those shapes.')
html+=pair('medieval-frame-oblique.png','Closed native ring:117 outline vertices,488 triangles and732 edges checked for paired opposite winding.3.5cm depth is inferred; uniform rear/sides and carved relief still need source validation.','medieval-panel-magdalene.png','Separate authentic painted panel sits1cm behind the front lip. Original crop pixels verified equal; dimensions provisionally treated as painted-panel size.')
html+=pair('panel-85.75.png','Source wide: Virgin on west wall; Magdalene and Saint Peter on north wall.','medieval-north-panel-wide.png','Current wall grouping with all four newly built medieval paintings. Spacing is source-guided; room metres, heights, supports and exact offsets are not accepted.')
html+='<h2>Architecture still needing correction</h2><p>The source has a flat off-white medieval ceiling. The prototype omitted opaque room ceilings for its elevated walking camera; at eye height this can expose the unrelated Main Hall skylight. That is an identified geometry defect, not source acceptance. The next correction will add the evidenced ceilings and verify eye-level/top-down visibility.</p>'
html+=pair('grille-88.75-review.jpg','Reciprocal video wide: flat ceiling, tracks, iron grille to the portal right, stone fragment by stair door, low case.','medieval-portal-wall-wide.png','Current portal wall: grille/stone fragment/ceiling remain unfinished. Display cases, room heights and portal reverse also need refinement.')
html+=pair('grille-12.25-review.jpg','Tall repeated spiral ironwork, projecting white plinth and rear diagonal brace. Official API candidates checked so far do not match.','hall-wide-arch.png','Existing Main Hall connection and23 original paintings retained; palette and portal reverse remain under review.')
html+=f'<p>Current RTX4070SUPER Chrome154/154 navigation/camera checks plus keyboard round trip,errors[],p95{b["engine"]["frame_time_p95_ms"]:.2f}ms,ready{b["first_ready_ms"]}ms locally.799 baked surfaces; final CPU Vulkan bake390.81s. Native close/oblique/wide views inspected. Owning Shell repeat{passed}/50,{failed} failures retained; first44/50 had two additional animation timing failures. Repository checks pass.60fps target remains unmet/unverified; no new native performance claim.</p><p>No new paid generation this pass. Total$0.74 actual/$0.75 conservative. Heartbeat disabled; sole main worker. Full reconstruction remains unfinished: accurate rooms/placements/lighting, remaining gallery objects and case contents, stairs, auditorium and modern gallery.</p><p><a href="native-geometry.json">Closed mesh checks</a> · <a href="source-fit.json">Source profile and uncertainty</a> · <a href="architecture-review.json">Architecture findings</a> · <a href="browser-result.json">Browser checks</a></p></main></html>'
(review/'index.html').write_text(html);(e/'review.html').write_text(html)
(public/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v42/"><a href="../architecture-review-v42/">Latest Collection reconstruction</a>')
base='https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'
for n in ['architecture-review-v42/','rockefeller-architecture-v42/','rockefeller-architecture-v42/index.pck']:
 with urllib.request.urlopen(base+n,timeout=30) as r:assert r.status==200
print('Published',base+'progress/')
