from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil,subprocess,tarfile,re
app=Path('image-work/collection-room-remodel');e=Path('docs/evidence/collection-reconstruction/main-worker-gabled-frame-20261001T0925');out=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion/lowpoly-room-v42b-gabled')
b=json.loads((out/'evidence/browser-result.json').read_text());assert b['pass'] and b['errors']==[] and len(b['engine']['checks'])==154 and all(b['engine']['checks'].values()) and 'NVIDIA' in b['webgl_renderer']
loop=[x for x in b['engine']['samples'] if x['trial'].startswith('loop_')];assert len(loop)==33 and all(x['started_without_reset'] for x in loop[1:])
shell=Path('/tmp/collection-v42b-shell-repeat.log').read_text();passed=len(re.findall(r'^PASS ',shell,re.M));failed=len(re.findall(r'^FAIL ',shell,re.M));assert passed+failed==50
first=Path('/tmp/collection-v42b-shell.log').read_text();first_passed=len(re.findall(r'^PASS ',first,re.M));assert first_passed==44
proof=json.loads((out/'evidence/magdalene-frame-native.json').read_text());assert proof['closed_edges']==732 and proof['triangles']==488 and proof['vertices']==244 and proof['signed_volume_m3']>0
assert 'checks passed' in Path('/tmp/collection-v42b-check.log').read_text();assert 'BAKE_OK users=799' in Path('/tmp/collection-v42b-bake.log').read_text();assert '[editor_plugins]' not in (out/'project.godot').read_text()
m=json.loads((out/'manifest.json').read_text())
for p,h in m['source_sha256'].items():assert hashlib.sha256(Path(p).read_bytes()).hexdigest()==h,p
r=json.loads((app/'reconstruction-coverage.json').read_text());r['current_preview']='https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/architecture-review-v42/';r['medieval_panels']['qa']={'browser_checks_passed':154,'browser_errors':[],'browser_frame_time_p95_ms':b['engine']['frame_time_p95_ms'],'baked_surfaces':799,'shell_passed':passed,'shell_first_passed':first_passed,'shell_total':50,'native_detail_views_inspected':True,'placement_accepted':False};r['medieval_panels']['next']='Fix source-evidenced missing opaque medieval/Renaissance ceilings using existing camera visibility; validate eye-level/top-down views. Then fit iron grille, east-wall fragments and stair connection.';(app/'reconstruction-coverage.json').write_text(json.dumps(r,indent=2)+'\n')
for n in ['manifest.json','geometry.json']:shutil.copyfile(out/n,e/n)
for n in ['reconstruction-coverage.json','sculpture-room-inventory.json']:shutil.copyfile(app/n,e/n)
for n in ['magdalene-frame-native.json','browser-result.json','medieval-frame-front.png','medieval-frame-oblique.png','medieval-panel-magdalene.png','medieval-north-panel-wide.png','medieval-portal-wall-wide.png','hall-wide-arch.png','loop-overview.png','browser-forward.png','browser-reverse.png']:shutil.copyfile(out/'evidence'/n,e/n)
for n in ['collection-v42-grille-source.py','collection-v42b-final-checks.py','collection-v42b-browser-with-server.py','collection-v41-bake.py','collection-publish-v42.py']:shutil.copyfile('/tmp/'+n,e/n)
logs=list(Path('/tmp').glob('collection-v42*.log'))
with tarfile.open(e/'raw-checks-and-shell-films.tar.gz','w:gz') as a:
 for p in logs:a.add(p,arcname=p.name)
 a.add('/tmp/collection-v42b-shell',arcname='owning-shell-first');a.add('/tmp/collection-v42b-shell-repeat',arcname='owning-shell-repeat')
for p in logs:(e/p.name).write_text('\n'.join(x.rstrip() for x in p.read_text().splitlines()).rstrip()+'\n')
entry=f'''\n### Collection v42 — source-fitted gabled frame (2026-10-01)\n\nNo new paid calls: reuse OpenRouter Muse corrected run56e0a4ec22f715cd28886116, native original unchanged. Total63 outputs plus previous$0.11:$0.74 actual/$0.75 conservative; ambiguous river-deities and failed headv1/v2 unchanged. Museum21.250 original crop pixels verified equal; source pentagon and117-vertex silhouette fit the generated gold by row-wise bands. Simplified outline/source mask overlap0.993992964. Initial threshold cut dark wood and nearest sampling exposed magenta: lower external mask threshold, small close and source-constrained nearest valid gold correct both; failed attempts were unpaid. Four native simple bands, closed front/back/outer/inner geometry:244 vertices,488 triangles,732 edges each paired with opposite winding; area0.03760449m²,positive volume0.001316157m³. Original painting separate and1cm inset.3.5cm frame depth, painted-panel interpretation22.5x49.5cm, plain sides/back, carving relief and placementx1.18/y1.55/z28.30 remain provisional/unaccepted. Source-shaped full frame0.2960x0.5848m.\n\n799 native users baked390.81s CPU Vulkan fallback; RTX4070SUPER close/front/oblique/wide views inspected. Original Main Hall23 works, six-room circuit and visitor retained. Chrome154/154 plus real keyboard round trip,p95{b['engine']['frame_time_p95_ms']:.3f}ms,errors[]. No new native performance claim. Owning Shell repeat{passed}/50,{failed} failures; first44/50 had2 additional animation timing failures. Both complete films/exact logs archived; readable logs trimmed at line ends. scripts/check.sh and git diff --check pass. All190 prepared source hashes and50 original pending hashes verified. Viewer/frozen seams untouched; no production integration or ticket closure.\n\nNative6382 12.25/13.25/14.25/88.75 confirms tall spiral ironwork on plinth right of portal, adjacent stone fragment and flat off-white ceiling. API searches/candidate photos retained;27.184 square gilt bronze with figure/floral ornament rejected,53.085 small clock grille does not establish the video installation. Grille identity remains unmatched. Root cause of erroneous skylight at eye height: room builder intentionally omits opaque ceilings for the elevated gallery camera; existing camera/ceiling visibility can retain opaque ceilings for source eye-level renders. Not fixed this pass. Next fix those ceilings, validate reciprocal wide/top-down views, then grille/east wall/stair doorway assets. Full rooms/placements/objects/lighting/stairs/auditorium/modern reconstruction and60fps target unfinished. Sole main worker, heartbeat disabled. Evidence `{e}/`.\n'''
Path('/tmp/collection-provenance-gabled-entry.md').write_text(entry);p=Path('modules/shell/PROVENANCE.md');assert not p.read_text().endswith(entry);p.write_text(p.read_text()+entry)
Path('/tmp/collection-v42-staged-provenance.md').write_bytes(subprocess.check_output(['git','show','HEAD:modules/shell/PROVENANCE.md'])+entry.encode())
s=p.read_bytes()
for n in ['gabled','panels','loop','perugino','bertin','cases','european-door','wide-scale','ionic','grey','full-survey','sculpture-layout','gallery','wide','inventory']:
 q=Path('/tmp/collection-provenance-'+n+'-entry.md').read_bytes();assert s.endswith(q),n;s=s[:-len(q)]
d=json.loads(Path('/tmp/collection-inventory-pending-before.json').read_text())
for path,h in d.items():assert hashlib.sha256(s if path=='modules/shell/PROVENANCE.md' else Path(path).read_bytes()).hexdigest()==h,path
(e/'preservation.json').write_text(json.dumps({'original_pending_files':len(d),'all_original_hashes_match':True,'prepared_source_count':len(m['source_sha256']),'all_source_hashes_match':True,'provenance_method':'Strip only15 session-authored entries; preserve original21 pending lines unstaged'},indent=2)+'\n')
failures='\n'.join(x.rstrip() for x in re.findall(r'^FAIL .*',shell,re.M));now=datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
(e/'CHECKPOINT.md').write_text(f'''# Collection checkpoint — {now}

Prototype v42. Sole main worker, heartbeat disabled. Goal active and unfinished. Viewer/frozen seams untouched; no production integration or ticket closure.

1. Corrected Muse Magdalene21.250 frame installed with separate original painted panel. Source pentagon and117-vertex outline,99.4% mask overlap;244 vertices/488 triangles/732 paired directed edges; positive volume confirms closed ring. Original crop pixels preserved. Source-guidedx1.18/y1.55/z28.30:0.82m left of Saint Peter consistent with two local ruler estimates0.805/0.830m, not absolute room proof.3.5cm depth, catalogue painted-panel-size interpretation, rear/relief, supports and exact mounting remain unaccepted. No new paid generation; cumulative$0.74 actual/$0.75 conservative, failed/ambiguous runs unchanged.
2.799 users baked390.81s CPU Vulkan fallback; final RTX native front/oblique/room-wide inspected. Original23 Hall works retained. Chrome154/154 plus real keyboard round trip;33 circuit segments without reset,p95{b['engine']['frame_time_p95_ms']:.3f}ms,ready{b['first_ready_ms']}ms,errors[]. No new native performance claim.60fps/remote cold-load target remains unmet or unverified. Shell repeat{passed}/50; first44/50 had two additional animation timing failures. Both films and raw logs retained. scripts/check.sh/git diff --check pass.190 source hashes and50 pending hashes match.
3. Four new CUDA-decoded native6382 clips12.25/13.25/14.25/88.75 reviewed. Spiral iron grille on low white plinth right of portal, rear diagonal brace/cast shadow, adjacent east-wall stone figure and flat off-white ceiling confirmed. Six API search terms and candidate reviews retained. Reject27.184: square gilt bronze/faces/floral scrolls differ.53.085 small bronze clock grille not evidence of tall installation. Grille remains unmatched and unbuilt.540x960 review JPEGs are derivatives; exact1080x1920 originals/hash manifest retained in ingestion.
4. Architecture defect identified: omitted opaque medieval ceiling reveals Hall skylight in eye-level wide. Builder comment says omitted for gallery camera. Next: add source-observed opaque medieval/Renaissance ceilings to bake and existing ceiling_details rule, show below3.4m eye and hide above for top-down; ensure bake preparation does not drop ceiling surfaces. Validate native eye-level reciprocal wide and actual walking camera before accepting. Do not restart an active successful bake merely for observation delays.
5. Then grille, east fragments/stair connection, remaining artwork/sculpture/case contents and source-correct placement/lighting; stairs, auditorium, modern gallery and overall measured geometry remain incomplete. All ten surveys were reviewed earlier; this does not prove complete reconstruction. No external blocker. Closed frame is a local geometry pass, not overall visual or owner acceptance.

Owning Shell repeat failures:

{failures}

https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/progress/

Reproduce: fit-magdalene-frame.py; prepare_remodel.py fresh output; saved bake helper with Mobile scene priming; RTX native review,Web export and browser wrapper; owning Shell. Exact raw logs are archived; readable log copies remove trailing whitespace. Current map/tickets remain open with their original scope.
''')
shutil.copyfile(__file__,e/'finish-checkpoint.py')
hashes={str(p.relative_to(e)):hashlib.sha256(p.read_bytes()).hexdigest() for p in e.rglob('*') if p.is_file() and p.name!='SHA256.json'};(e/'SHA256.json').write_text(json.dumps(hashes,indent=2)+'\n')
print('Evidence',len(hashes),'files; Shell repeat',passed,'/50; original pending preserved')
