// Issue #127: browser acceptance; run against the served web/ directory.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
const page = await browser.newPage({viewport:{width:1440,height:960}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
 await page.goto(process.env.VIEWER_URL || 'http://127.0.0.1:8137');
 await page.waitForSelector('.painting img');
 await page.waitForFunction(()=>[...document.querySelectorAll('.painting img')].every(i=>i.complete&&i.naturalWidth>0));
 const count=await page.locator('.painting').count();assert.ok(count>=5);
 const selected=()=>page.locator('.painting[aria-current="true"]');
 const first=await selected().getAttribute('data-index');
 await page.locator('#stage').focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(650);
 assert.equal(Number(await selected().getAttribute('data-index')),Number(first)+1);
 await page.mouse.move(700,350);await page.mouse.wheel(0,180);await page.waitForTimeout(700);
 assert.equal(Number(await selected().getAttribute('data-index')),Number(first)+2);
 await selected().click();await page.waitForSelector('dialog[open]');assert.ok(await page.locator('#large-image').getAttribute('src'));
 await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
 await page.locator('#stage').focus();await page.keyboard.press('End');await page.waitForTimeout(650);assert.equal(Number(await selected().getAttribute('data-index')),count-1);
 await page.keyboard.press('ArrowRight');await page.waitForTimeout(100);assert.equal(Number(await selected().getAttribute('data-index')),count-1);
 await page.keyboard.press('Home');await page.waitForTimeout(650);assert.equal(Number(await selected().getAttribute('data-index')),0);
 await page.keyboard.press('ArrowLeft');assert.equal(Number(await selected().getAttribute('data-index')),0);
 await page.locator('#next').click();await page.waitForTimeout(650);
 await mkdir(new URL('./evidence/',import.meta.url),{recursive:true});
 await page.screenshot({path:new URL('./evidence/desktop.png',import.meta.url).pathname});
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#next').click();await page.waitForTimeout(650);assert.equal(Number(await selected().getAttribute('data-index')),2);
 await page.screenshot({path:new URL('./evidence/mobile.png',import.meta.url).pathname});
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#previous').click();await page.waitForTimeout(50);
 assert.equal(Number(await selected().getAttribute('data-index')),1);
 await page.setViewportSize({width:1440,height:960});
 await selected().focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(50);
 await page.keyboard.press('Enter');await page.waitForSelector('dialog[open]');
 assert.equal(await page.locator('#detail-title').textContent(),await page.locator('#title').textContent());
 await page.keyboard.press('Escape');
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.locator('#scrubber').fill('2');await page.waitForTimeout(650);
 await page.locator('#next').click();await page.waitForTimeout(80);
 const halfway=Number(await page.locator('#stage').getAttribute('data-position'));
 assert.ok(halfway>2&&halfway<3);
 await page.locator('#previous').click();await page.waitForTimeout(650);
 assert.equal(await page.locator('#stage').getAttribute('data-position'),'2.0000');
 const b=await page.locator('#stage').boundingBox(),y=b.y+b.height/2;
 await page.mouse.move(760,y);await page.mouse.down();await page.mouse.move(350,y,{steps:20});await page.mouse.up();await page.waitForTimeout(650);
 assert.equal(Number(await selected().getAttribute('data-index')),3);
 assert.equal(await page.locator('dialog[open]').count(),0);
 await page.locator('#scrubber').fill('2');await page.waitForTimeout(650);
 const side=await page.locator('.painting[data-index="1"]').boundingBox();
 await page.mouse.click(side.x+side.width*.25,side.y+side.height*.5);await page.waitForTimeout(650);
 assert.equal(Number(await selected().getAttribute('data-index')),1);
 await page.setViewportSize({width:390,height:844});
 await page.locator('#scrubber').fill('2');await page.waitForTimeout(650);
 const mobile=await page.locator('#stage').boundingBox(),ty=mobile.y+mobile.height*.6;
 const cdp=await page.context().newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:280,y:ty}]});
 for(let x=270;x>=115;x-=15){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:ty}]});await page.waitForTimeout(16);}
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(650);
 assert.equal(Number(await selected().getAttribute('data-index')),3);
 assert.deepEqual(errors,[]);console.log(`PASS: ${count} loaded paintings; keyboard, wheel, open/close, bounds, controls, mobile, reduced motion, keyboard focus, smooth interruption, neighbor click, drag and touch; no page errors.`);
} finally { await browser.close(); }
