from pathlib import Path
import json,shutil,urllib.request,html
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v40-loop';share=root/'review-preview';review=share/'architecture-review-v40';e=Path('docs/evidence/collection-reconstruction/main-worker-connected-loop-20261001T0735')
a=json.loads((out/'evidence/walk-result.json').read_text());b=json.loads((out/'evidence/browser-result.json').read_text());assert len(a['checks'])==154 and all(a['checks'].values()) and b['pass'];assert 'NVIDIA' in a['renderer'] and 'NVIDIA' in b['webgl_renderer']
for report in [a,b['engine']]:
 loop=[s for s in report['samples'] if s['trial'].startswith('loop_')];assert len(loop)==33 and all(s['started_without_reset'] for s in loop[1:])
review.mkdir(exist_ok=False);shutil.copytree(out/'web',share/'rockefeller-architecture-v40')
for name in ['hall-wide-arch','hall-wide-far','hall-west-paintings','hall-source-camera','hall-grey-join','hall-portal-join','hall-walk','hall-portal-walk','loop-overview','medieval-portal-wall-wide','medieval-cases-east','medieval-cases-portal','renaissance-wide','grey-gallery-wide','perugino-in-room','portal-front','portal-angle','browser-forward','browser-reverse','browser-jamb']:
 shutil.copyfile(out/'evidence'/f'{name}.png',review/f'{name}.png');shutil.copyfile(out/'evidence'/f'{name}.png',e/f'{name}.png')
for name in ['medieval-85.25.png','medieval-86.25.png','medieval-87.25.png','medieval-89.25.png','source-hall-177.50.png','risd-official-floor5-map.png','route-plan.svg','medieval-pan-contact.jpg','hall-first-warm.png']:
 shutil.copyfile(e/name,review/name)
shutil.copyfile(root/'hall-wide-native-v1/hall-65.00.png',review/'source-hall-65.00.png');shutil.copyfile(root/'hall-wide-native-v1/hall-65.00.png',e/'source-hall-65.00.png')
for name in ['walk-result.json','browser-result.json']:shutil.copyfile(out/'evidence'/name,e/name);shutil.copyfile(out/'evidence'/name,review/name)
for name in ['geometry.json','manifest.json']:shutil.copyfile(out/name,e/name);shutil.copyfile(out/name,review/name)
shutil.copyfile('image-work/collection-room-remodel/reconstruction-coverage.json',e/'reconstruction-coverage.json')
def fig(name,text):return f'<figure><a href="{name}"><img src="{name}" alt="{html.escape(text)}" loading="lazy"></a><figcaption>{html.escape(text)}</figcaption></figure>'
def pair(x,y):return '<div class="pair">'+x+y+'</div>'
body='<h1>Collection · connected museum loop</h1><p><a href="../rockefeller-architecture-v40/">Walk the connected rooms</a> · <a href="../architecture-review-v39/">Previous pass</a></p><p>WASD to walk, Space returns to the start. Press 2 for the European gallery or 3 for the French gallery. The circuit goes through Rockefeller, European, Renaissance, medieval, Grand Gallery and French rooms. Exact room measurements and complete object placement remain provisional.</p>'
body+=pair(fig('route-plan.svg','Authored layout and red walking circuit. Shared openings and no room overlap checked; connector length and room dimensions unaccepted.'),fig('loop-overview.png','Rendered plan of the connected prototype. Long galleries meet the two end rooms; stairs remain threshold studies. Blank space has no invented connection.'))
body+=pair(fig('source-hall-177.50.png','Original Hall177.50s. Native video retained as reference only; no video textures in the room.'),fig('hall-source-camera.png','Current Hall with23 reused original museum paintings and Muse frames. Approximate eye/tilt for comparison, not a calibrated camera. Frame heights, wall tone and exact placement require further verification.'))
body+=pair(fig('source-hall-65.00.png','Second native Hall view65.00s: white casing, stone intrados and the two paintings.'),fig('hall-wide-arch.png','Current Hall end: white Muse moulding, plain unverified reverse of the stone portal, real opening into medieval. Carved facade stays on its medieval front. Background crucifix and other medieval works remain missing.'))
body+=pair(fig('hall-wide-far.png','Opposite Hall end opens directly into the French gallery. The old photo doorway cards and fabricated vestibules are replaced by the existing authored room.'),fig('hall-grey-join.png','Eye-height through the actual French-gallery connection. No teleport or isolated Hall scene.'))
body+=pair(fig('medieval-85.25.png','Native6382 85.25s: west-wall corner and two gold panels on the north wall.'),fig('medieval-87.25.png','The projecting grey/black display panel beside the arch is not the room corner. The north-wall paintings precede it across the pan.'))
body+=pair(fig('medieval-89.25.png','Native right side of portal: iron grille, east corner and stairs door. Source positions still need metric fitting.'),fig('medieval-portal-wall-wide.png','Authored wider portal wall. Architecture is connected; the north paintings, projecting display and iron grille are not yet instantiated.'))
body+=pair(fig('portal-front.png','Corrected source-facing carved portal. Existing Muse front reused; stepped extrusion, intrados, rear and depth remain unaccepted.'),fig('portal-angle.png','Oblique view through the physical Hall connection. This is an authored silhouette, not finished architectural geometry.'))
matches=json.loads((e/'medieval-catalogue-matches.json').read_text())['matched']
body+='<h2>Verified identities; assets still missing</h2><p>The wide review corrected the wall assignment and several mistaken titles. These six works match official catalogue photos and the supplied video. Their object geometry and placement are still to be built.</p><ul>'
for row in matches:body+=f'<li><a href="{html.escape(row["url"])}">{html.escape(row["accession"])}</a>: {html.escape(row["appearance_match"])}</li>'
body+='</ul>'
for name in ['memmi-magdalene-zoom-0.jpg','taking-peter-zoom-0.jpg','medieval-survey-146.jpg','medieval-survey-152.jpg']:shutil.copyfile(e/name,review/name)
body+=pair(fig('memmi-magdalene-zoom-0.jpg','North-wall gabled panel: Mary Magdalene21.250, Lippo Memmi. Authentic art and sculpted frame need separate treatment.'),fig('taking-peter-zoom-0.jpg','North-wall horizontal panel: The Taking of Saint Peter22.047, Jacopo di Cione. Source offsets unaccepted.'))
body+=pair(fig('hall-walk.png','Actual Main Hall376x252 walking presentation, same page art, screen shaders and visitor.'),fig('hall-portal-walk.png','Walking through the Hall toward the medieval connection. Camera cutaway keeps the same physical wall collisions.'))
body+=pair(fig('renaissance-wide.png','Renaissance painting, bench and tracery remain source-relative within the moved room; its other wall works/case contents are incomplete.'),fig('medieval-cases-east.png','Two source-relative case shells retained. Their offsets, contents and hidden profiles remain unaccepted.'))
body+=fig('risd-official-floor5-map.png','Current RISD guide links this2020 schematic. Used for room topology, never for scale or current object hang.')
body+=f'<p>RTX native154/154 and RTX Chrome154/154 checks pass, including33 consecutive circuit segments and32 transitions without reset. Native p95{a["frame_time_p95_ms"]:.2f}ms; Chrome p95{b["engine"]["frame_time_p95_ms"]:.2f}ms.769 native lightmap users.60fps target is not met. Owning Shell repeat46/50: four existing pixel/layout failures. First43/50 included three additional timing failures that did not recur; both runs retained. Repository checks pass. Full outputs are in the dated checkpoint.</p><p>No new paid generation: reuse the existing Hall Muse assets and native architectural mouldings. Expansion spend remains$0.72 actual/$0.73 conservative. Heartbeat is disabled; sole main worker.</p><p>Still unfinished: independent room-scale validation, accurate object-by-object placement, missing medieval/Renaissance/European/French objects, historic and piano stairs, Metcalf Auditorium and modern gallery. Next: verify and place the four medieval north/west gold panels and iron grille from the API and reciprocal video views.</p>'
body+='<p><a href="walk-result.json">Native checks</a> · <a href="browser-result.json">Chrome checks</a> · <a href="geometry.json">Authored layout</a> · <a href="https://risdmuseum.org/visitor-guide/floor-5">RISD floor-five guide</a></p>'
style='body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto;max-height:1100px;object-fit:contain}figcaption{margin:6px 0 24px}'
page='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection connected museum loop</title><style>'+style+'</style><main>'+body+'</main></html>'
(review/'index.html').write_text(page);(e/'review.html').write_text(page);(share/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v40/"><a href="../architecture-review-v40/">Latest Collection reconstruction</a>')
for path in ['progress/','architecture-review-v40/','rockefeller-architecture-v40/index.pck']:
 with urllib.request.urlopen('https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'+path,timeout=20) as r:assert r.status==200;print(path,r.status,r.headers.get('Content-Length'))
