import { expect, test } from '@playwright/test'

test('D fixes the supplied header above the unchanged sketchbook', async ({ page }) => {
  await page.goto('./?variant=D')
  const header = page.getByTestId('reference-viewer-window')
  const book = page.getByTestId('japanese-book-stage')
  await expect(book).toBeVisible()
  await expect(page.getByTestId('reference-above-panel')).toHaveAttribute('src', /header-layout-source\.png$/)
  const frame = await page.getByTestId('japanese-utility-window').boundingBox()
  const stage = await book.boundingBox()
  const before = await header.boundingBox()
  if (!frame || !stage || !before) throw Error('Missing header or sketchbook')
  expect(frame.width).toBe(980)
  expect(frame.height).toBe(900)
  expect(stage.width).toBe(952)
  expect(stage.height).toBe(714)
  expect(frame.y).toBeGreaterThanOrEqual(before.y + before.height)
  const pane = page.getByTestId('sketchbook-scroll-pane')
  await pane.evaluate(element => { element.scrollTop = 320 })
  expect(await pane.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  const after = await header.boundingBox()
  const scrolledBook = await book.boundingBox()
  expect(after).toEqual(before)
  expect(scrolledBook?.width).toBe(stage.width)
  expect(scrolledBook?.height).toBe(stage.height)
  expect(scrolledBook!.y).toBeLessThan(stage.y)
})
