from pathlib import Path
from PIL import Image
import json,shutil,urllib.request
root=Path('/home/reidsurmeier/risd-godot-ingestion/collection-expansion');out=root/'lowpoly-room-v35';share=root/'review-preview';review=share/'architecture-review-v35';e=Path('docs/evidence/collection-reconstruction/main-worker-european-door-20261001T0500');app=Path('image-work/collection-room-remodel')
a=json.loads((out/'evidence/walk-result.json').read_text());b=json.loads((out/'evidence/browser-result.json').read_text());assert all(a['checks'].values()) and b['pass'];assert 'NVIDIA' in a['renderer'] and 'NVIDIA' in b['webgl_renderer']
review.mkdir(exist_ok=True);shutil.copytree(out/'web',share/'rockefeller-architecture-v35',dirs_exist_ok=True)
for name in ['european-door-detail','european-door-reverse','gallery-far-door','renaissance-wide','phase-11','phase-12','browser-forward','browser-reverse','browser-jamb']:
 shutil.copyfile(out/'evidence'/f'{name}.png',review/f'{name}.png');shutil.copyfile(out/'evidence'/f'{name}.png',e/f'{name}.png')
for sec in ['102.75','104.75']:
 im=Image.open(e/f'source-leaf-{sec}.png');im.thumbnail((850,850));im.save(review/f'source-leaf-{sec}.png')
im=Image.open(app/'trial/european-two-panel-door-original.webp');im.thumbnail((850,850));im.save(review/'muse-door.webp')
for name in ['walk-result.json','browser-result.json']:shutil.copyfile(out/'evidence'/name,e/name);shutil.copyfile(out/'evidence'/name,review/name)
for name in ['geometry.json','manifest.json']:shutil.copyfile(out/name,review/name)
def figure(path,caption):return f'<figure><img src="{path}" alt="{caption}" loading="lazy"><figcaption>{caption}</figcaption></figure>'
body='<h1>Collection rooms · doorway correction</h1><p><a href="../rockefeller-architecture-v35/">Walk the latest rooms</a> · <a href="../architecture-review-v34/">Previous room and Ionic architecture review</a> · <a href="../architecture-review-v34/wide-scale/">Wide-view scale study</a></p><p>Press 2 to jump to the European gallery, then walk to its far double doors. WASD moves; Space resets.</p><p>Wide shots showed that the European-to-Renaissance leaves were backwards and had the wrong panels. The prototype now swings them into the Renaissance room and replaces three equal panels with a tall upper panel and a shorter lower panel.</p><div class="pair">'+figure('source-leaf-102.75.png','Actual left leaf and its swing into Renaissance, IMG_6386 102.75s.')+figure('source-leaf-104.75.png','Reciprocal right leaf, IMG_6386 104.75s.')+'</div><div class="pair">'+figure('gallery-far-door.png','Corrected pair seen from the European gallery. Most Renaissance contents are still missing.')+figure('european-door-reverse.png','Reverse view into the European gallery; existing room dimensions remain provisional.')+'</div><div class="pair">'+figure('muse-door.webp','One Muse pass, $0.01. Invented narrow middle strip discarded; only the two large panel fields are used.')+figure('european-door-detail.png','Native thickness and panel relief. Panels remain too dark; exact moulding depth and palette are unaccepted.')+'</div><p>Native and Chrome on RTX 4070 SUPER pass 58/58 collision/camera checks, including both leaf collisions, plus the browser keyboard round trip. Native p95'+str(round(a['frame_time_p95_ms'],2))+'ms; browser p95'+str(round(b['engine']['frame_time_p95_ms'],2))+'ms. Performance remains below the 60fps target. Repository checks pass; owning Shell 44/50 with the recorded layout/tint/timing failures. One additional Muse request, cumulative $0.70 actual/$0.71 conservative.</p><div class="pair">'+figure('phase-11.png','Left leaf blocks the visitor; camera remains clear.')+figure('phase-12.png','Right leaf collision; clear central crossing.')+'</div><p>Full reconstruction is unfinished. Hall entrance spacing remains inconsistent; most Renaissance/medieval artwork, cases and sculptures remain unplaced. Next: fit the adjoining room offsets from wide views before joining the full Main Hall. Heartbeat stays disabled; Collection only.</p>'
style='body{font:17px/1.5 system-ui;background:#f3eee3;color:#302b23;max-width:1200px;margin:40px auto;padding:20px}a{color:#335f7a}.pair{display:flex;gap:20px;flex-wrap:wrap}.pair figure{flex:1;min-width:250px;margin:0}img{width:100%;height:auto}figcaption{margin:6px 0 24px}'
page='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Collection doorway correction</title><style>'+style+'</style><main>'+body+'</main></html>'
(review/'index.html').write_text(page);(e/'review.html').write_text(page)
(share/'progress/index.html').write_text('<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=../architecture-review-v35/"><a href="../architecture-review-v35/">Latest Collection reconstruction</a>')
for path in ['progress/','architecture-review-v35/','rockefeller-architecture-v35/index.pck']:
 with urllib.request.urlopen('https://windows-wsl.taile06c45.ts.net/risd-frame-review-01a0ee18/'+path,timeout=20) as r:assert r.status==200;print(path,r.status,r.headers.get('Content-Length'))
